
import type { Listing, User, AdminDashboardMetrics, VerificationRequestItem, ReadyToEngageItem, Inquiry, NotificationItem, InquiryStatusSystem, InquiryStatusBuyerPerspective, InquiryStatusSellerPerspective } from './types';

export const sampleUsers: User[] = [
  {
    id: 'user1',
    fullName: 'John Doe (Seller)',
    email: 'john.seller@example.com',
    phoneNumber: '+6591234567',
    country: 'Singapore',
    role: 'seller',
    isEmailVerified: true,
    verificationStatus: 'verified',
    isPaid: true, 
    initialCompanyName: 'JD Web Solutions',
    createdAt: new Date('2023-01-10T09:00:00Z'),
    updatedAt: new Date('2023-01-15T14:30:00Z'),
  },
  {
    id: 'user2',
    fullName: 'Jane Smith (Buyer)',
    email: 'jane.buyer@example.com',
    phoneNumber: '+60123456789',
    country: 'Malaysia',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'verified',
    isPaid: true, 
    buyerType: 'Individual Investor',
    createdAt: new Date('2023-02-05T11:00:00Z'),
    updatedAt: new Date('2023-02-05T11:00:00Z'),
  },
  {
    id: 'user3',
    fullName: 'Alex Tan (Seller - Anonymous)',
    email: 'alex.seller.anon@example.com',
    phoneNumber: '+84987654321',
    country: 'Vietnam',
    role: 'seller',
    isEmailVerified: true,
    verificationStatus: 'anonymous',
    isPaid: false,
    initialCompanyName: 'Anonymous SaaS Co.',
    createdAt: new Date('2023-03-20T16:00:00Z'),
    updatedAt: new Date('2023-03-20T16:00:00Z'),
  },
   {
    id: 'user4',
    fullName: 'Sarah Chen (Buyer - Pending)',
    email: 'sarah.buyer.pending@example.com',
    phoneNumber: '+1234567890',
    country: 'Thailand',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'pending_verification',
    isPaid: false, 
    buyerType: 'Investment Firm',
    createdAt: new Date('2023-04-10T10:00:00Z'),
    updatedAt: new Date('2023-04-10T10:00:00Z'),
  },
  {
    id: 'user5',
    fullName: 'Michael Lee (Buyer - Free)',
    email: 'michael.freebuyer@example.com',
    phoneNumber: '+6281234567890',
    country: 'Indonesia',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'verified', 
    isPaid: false,
    buyerType: 'Strategic Acquirer',
    createdAt: new Date('2023-05-01T11:00:00Z'),
    updatedAt: new Date('2023-05-01T11:00:00Z'),
  },
  {
    id: 'user6',
    fullName: 'Anna Tay (Buyer - Anonymous)',
    email: 'anna.buyer.anon@example.com',
    phoneNumber: '+639171234567',
    country: 'Philippines',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'anonymous',
    isPaid: false,
    buyerType: 'Individual Investor',
    createdAt: new Date('2023-06-15T09:00:00Z'),
    updatedAt: new Date('2023-06-15T09:00:00Z'),
  },
];

export const sampleListings: Listing[] = [
  {
    id: '1',
    sellerId: 'user1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    industry: 'E-commerce',
    locationCountry: 'Singapore',
    locationCityRegionGeneral: 'Nationwide',
    anonymousBusinessDescription: 'Thriving online retail business with a strong brand presence and loyal customer base. Specializes in eco-friendly products. Consistent growth year-over-year. Huge potential for expansion into new markets and product lines.',
    keyStrengthsAnonymous: ['Strong Brand Recognition', 'High Customer Retention', 'Scalable Operations'],
    annualRevenueRange: '$500K - $1M USD',
    netProfitMarginRange: '20% - 30%',
    askingPriceRange: '$1M - $2.5M USD',
    dealStructureLookingFor: ['Full Acquisition'],
    reasonForSellingAnonymous: 'Owner retiring.',
    status: 'active',
    isSellerVerified: true,
    actualCompanyName: 'GreenEarth Goods Pte. Ltd.',
    fullBusinessAddress: '123 Orchard Road, Singapore',
    specificAnnualRevenueLastYear: 750000,
    specificNetProfitLastYear: 180000,
    createdAt: new Date('2023-10-15T10:00:00Z'),
    updatedAt: new Date('2023-10-15T10:00:00Z'),
    imageUrl: 'https://placehold.co/600x400.png',
    potentialForGrowthNarrative: 'Significant growth potential by expanding product catalog to adjacent niches and targeting new customer segments in neighboring ASEAN countries. Current marketing efforts are minimal, offering substantial upside with a dedicated marketing strategy.',
    financialSnapshotUrl: '/documents/placeholder-financials.pdf',
    ownershipDetailsUrl: '/documents/placeholder-ownership.pdf',
    locationRealEstateInfoUrl: '/documents/placeholder-lease.pdf',
    webPresenceInfoUrl: '/documents/placeholder-web-analytics.pdf',
    inquiryCount: 5,
  },
  {
    id: '2',
    sellerId: 'user3',
    listingTitleAnonymous: 'Established SaaS Platform - B2B Niche',
    industry: 'Software',
    locationCountry: 'Vietnam',
    locationCityRegionGeneral: 'Ho Chi Minh City Area',
    anonymousBusinessDescription: 'Innovative SaaS solution catering to a specific B2B vertical. Growing subscriber base with high MRR. Lean operations, ready for scaling with marketing investment. Solid tech stack.',
    keyStrengthsAnonymous: ['Unique Market Position', 'Recurring Revenue Model', 'High Growth Potential'],
    annualRevenueRange: '$100K - $250K USD',
    askingPriceRange: '$250K - $500K USD',
    dealStructureLookingFor: ['Full Acquisition', 'Partial Sale/Investment'],
    status: 'active',
    isSellerVerified: false,
    createdAt: new Date('2023-11-01T14:30:00Z'),
    updatedAt: new Date('2023-11-01T14:30:00Z'),
    imageUrl: 'https://placehold.co/600x400.png',
    potentialForGrowthNarrative: 'The platform is poised for rapid expansion with further development of enterprise features and targeted sales efforts in the APAC region. Untapped potential in complementary service integrations.',
    inquiryCount: 2,
  },
  {
    id: '3',
    sellerId: 'user1', 
    listingTitleAnonymous: 'Boutique Marketing Agency',
    industry: 'Services - Marketing',
    locationCountry: 'Malaysia',
    locationCityRegionGeneral: 'Kuala Lumpur',
    anonymousBusinessDescription: 'Creative marketing agency with a portfolio of SME clients. Specializes in digital marketing and content creation. Strong local reputation. Team of 5 experienced professionals.',
    keyStrengthsAnonymous: ['Strong Client Relationships', 'Creative Team', 'Diverse Service Offering'],
    annualRevenueRange: '$250K - $500K USD',
    netProfitMarginRange: '10% - 20%',
    askingPriceRange: '$500K - $1M USD',
    status: 'active',
    isSellerVerified: true,
    actualCompanyName: 'Creative Spark Solutions Sdn. Bhd.',
    createdAt: new Date('2023-09-20T08:00:00Z'),
    updatedAt: new Date('2023-09-20T08:00:00Z'),
    imageUrl: 'https://placehold.co/600x400.png',
    potentialForGrowthNarrative: 'Opportunity to scale by expanding service offerings to larger corporate clients and developing proprietary marketing tools. Strong referral network provides a solid base for growth.',
    financialSnapshotUrl: '/documents/placeholder-agency-financials.pdf',
    webPresenceInfoUrl: 'https://example-agency.com',
    inquiryCount: 1,
  },
   {
    id: '4',
    sellerId: 'user3',
    listingTitleAnonymous: 'Modern Cafe in Tourist Hotspot',
    industry: 'Retail',
    locationCountry: 'Thailand',
    locationCityRegionGeneral: 'Phuket',
    anonymousBusinessDescription: 'Popular cafe with excellent reviews and high foot traffic. Known for specialty coffee and unique menu. Turnkey operation with trained staff. Strong social media presence.',
    keyStrengthsAnonymous: ['Prime Location', 'Established Reputation', 'Loyal Customer Base', 'High Online Ratings'],
    annualRevenueRange: '$100K - $250K USD',
    netProfitMarginRange: '15% - 25%',
    askingPriceRange: '$150K - $300K USD',
    status: 'pending_verification',
    isSellerVerified: false,
    createdAt: new Date('2023-12-01T09:00:00Z'),
    updatedAt: new Date('2023-12-01T09:00:00Z'),
    imageUrl: 'https://placehold.co/600x400.png',
    inquiryCount: 0,
  },
];

export const sampleBuyerInquiries: Inquiry[] = [
  {
    id: 'inq_b1',
    listingId: '1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user2', // Jane Smith (Verified Buyer)
    inquiryTimestamp: new Date('2023-11-10T10:00:00Z'),
    sellerStatus: 'Platform Verified Seller',
    status: 'ready_for_admin_connection' as InquiryStatusSystem, 
    statusBuyerPerspective: 'Ready for Admin Connection' as InquiryStatusBuyerPerspective,
    createdAt: new Date('2023-11-10T10:00:00Z'),
    updatedAt: new Date('2023-11-11T10:00:00Z'),
  },
  {
    id: 'inq_b2',
    listingId: '2',
    listingTitleAnonymous: 'Established SaaS Platform - B2B Niche',
    sellerId: 'user3',
    buyerId: 'user2', // Jane Smith (Verified Buyer)
    inquiryTimestamp: new Date('2023-11-08T15:30:00Z'),
    sellerStatus: 'Anonymous Seller',
    status: 'new_inquiry' as InquiryStatusSystem,
    statusBuyerPerspective: 'Inquiry Sent' as InquiryStatusBuyerPerspective,
    createdAt: new Date('2023-11-08T15:30:00Z'),
    updatedAt: new Date('2023-11-08T15:30:00Z'),
  },
  {
    id: 'inq_b3',
    listingId: '1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user6', // Anna Tay (Anonymous Buyer)
    inquiryTimestamp: new Date('2023-11-12T09:00:00Z'),
    sellerStatus: 'Platform Verified Seller',
    status: 'seller_engaged_buyer_pending_verification' as InquiryStatusSystem, 
    statusBuyerPerspective: 'Seller Engaged - Your Verification Required' as InquiryStatusBuyerPerspective,
    createdAt: new Date('2023-11-12T09:00:00Z'),
    updatedAt: new Date('2023-11-12T10:00:00Z'),
  },
];

export const sampleSellerInquiries: Inquiry[] = [
  {
    id: 'inq_s1',
    listingId: '1', // John Doe's Listing
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user2', // Jane Smith
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    inquiryTimestamp: new Date('2023-11-10T10:00:00Z'),
    status: 'ready_for_admin_connection' as InquiryStatusSystem,
    statusSellerPerspective: 'Ready for Admin Connection' as InquiryStatusSellerPerspective,
    createdAt: new Date('2023-11-10T10:00:00Z'),
    updatedAt: new Date('2023-11-11T10:00:00Z'),
  },
  {
    id: 'inq_s2',
    listingId: '1', // John Doe's Listing
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user6', // Anna Tay
    buyerName: 'Anna Tay (Buyer - Anonymous)',
    buyerVerificationStatus: 'anonymous',
    inquiryTimestamp: new Date('2023-11-12T09:00:00Z'),
    status: 'new_inquiry' as InquiryStatusSystem,
    statusSellerPerspective: 'New Inquiry' as InquiryStatusSellerPerspective,
    createdAt: new Date('2023-11-12T09:00:00Z'),
    updatedAt: new Date('2023-11-12T09:00:00Z'),
  },
   {
    id: 'inq_s3',
    listingId: '2', // Alex Tan's Listing
    listingTitleAnonymous: 'Established SaaS Platform - B2B Niche',
    sellerId: 'user3',
    buyerId: 'user2', // Jane Smith
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    inquiryTimestamp: new Date('2023-11-08T15:30:00Z'),
    status: 'new_inquiry' as InquiryStatusSystem,
    statusSellerPerspective: 'New Inquiry' as InquiryStatusSellerPerspective,
    createdAt: new Date('2023-11-08T15:30:00Z'),
    updatedAt: new Date('2023-11-08T15:30:00Z'),
  },
];


export const sampleAdminDashboardMetrics: AdminDashboardMetrics = {
  newUserRegistrations24h: 5,
  newUserRegistrations7d: 23,
  newListingsCreated24h: 2,
  newListingsCreated7d: 10,
  totalActiveSellers: 58, 
  totalActiveBuyers: 120,  
  totalActiveListingsAnonymous: 35, 
  totalActiveListingsVerified: 15, 
  buyerVerificationQueueCount: 3, 
  sellerVerificationQueueCount: 4, 
  readyToEngageQueueCount: 3,
  paidBuyersCount: 40,
  freeBuyersCount: 80,
  paidSellersCount: 25,
  freeSellersCount: 33,
  totalRevenue: 12500, 
  successfulConnectionsCount: 12, 
  closedDealsCount: 4,
};

export const sampleVerificationRequests: VerificationRequestItem[] = [
  {
    id: 'vr1',
    timestamp: new Date('2023-11-10T10:00:00Z'),
    userId: 'user4', 
    userName: 'Sarah Chen (Buyer - Pending)',
    userRole: 'buyer',
    reason: 'New buyer registration, requires profile verification.',
  },
  {
    id: 'vr2',
    timestamp: new Date('2023-11-09T15:30:00Z'),
    userId: 'user3', 
    userName: 'Alex Tan (Seller - Anonymous)',
    userRole: 'seller',
    listingId: '2',
    listingTitle: 'Established SaaS Platform - B2B Niche',
    reason: 'Seller submitted new listing, requires seller and listing verification.',
  },
  {
    id: 'vr3',
    timestamp: new Date('2023-11-11T11:00:00Z'),
    userId: 'user5', 
    userName: 'Michael Lee (Buyer - Free)',
    userRole: 'buyer',
    reason: 'Buyer requested manual verification upgrade.',
  },
   {
    id: 'vr4',
    timestamp: new Date('2023-11-12T09:00:00Z'),
    userId: 'newSellerUser123', 
    userName: 'Pending Seller Alpha',
    userRole: 'seller',
    reason: 'New seller account created.',
  },
];

export const sampleReadyToEngageItems: ReadyToEngageItem[] = [
  {
    id: 'rte1',
    timestamp: new Date('2023-11-08T12:00:00Z'),
    buyerId: 'user2', 
    buyerName: 'Jane Smith (Buyer)',
    sellerId: 'user1', 
    sellerName: 'John Doe (Seller)',
    listingId: '1',
    listingTitle: 'Profitable E-commerce Store in SEA',
  },
];

export const sampleBuyerNotifications: NotificationItem[] = [
  {
    id: 'notif1_buyer2',
    userId: 'user2', // Jane Smith (Verified Buyer)
    timestamp: new Date('2023-11-11T10:05:00Z'),
    message: "Great news! Both you and the Seller for listing 'Profitable E-commerce Store in SEA' are verified and have agreed to engage. Our team will be in touch shortly.",
    link: '/dashboard/inquiries#inq_b1', // Link to specific inquiry
    isRead: false,
    type: 'engagement'
  },
  {
    id: 'notif2_buyer6',
    userId: 'user6', // Anna Tay (Anonymous Buyer)
    timestamp: new Date('2023-11-12T10:05:00Z'),
    message: "The seller of 'Profitable E-commerce Store in SEA' is ready to engage! To proceed, your profile needs to be verified.",
    link: '/dashboard/verification',
    isRead: false,
    type: 'verification'
  },
  {
    id: 'notif3_buyer2',
    userId: 'user2',
    timestamp: new Date('2023-11-09T08:00:00Z'),
    message: "Your profile information was successfully updated.",
    isRead: true,
    type: 'system'
  }
];

export const sampleSellerNotifications: NotificationItem[] = [
  {
    id: 'notif1_seller1',
    userId: 'user1', // John Doe (Seller)
    timestamp: new Date('2023-11-12T09:05:00Z'),
    message: "You have a new inquiry for your listing 'Profitable E-commerce Store in SEA' from Anna Tay (Buyer - Anonymous).",
    link: '/seller-dashboard/inquiries#inq_s2',
    isRead: false,
    type: 'inquiry'
  },
  {
    id: 'notif2_seller3',
    userId: 'user3', // Alex Tan (Seller - Anonymous)
    timestamp: new Date('2023-11-13T11:00:00Z'),
    message: "You've chosen to engage with Jane Smith regarding 'Established SaaS Platform - B2B Niche'. To proceed, your listing needs to be verified.",
    link: '/seller-dashboard/verification?listingId=2',
    isRead: false,
    type: 'verification'
  },
  {
    id: 'notif3_seller1',
    userId: 'user1',
    timestamp: new Date('2023-11-11T10:05:00Z'),
    message: "Great news! Both you and Jane Smith (Buyer) for listing 'Profitable E-commerce Store in SEA' are verified and have agreed to engage. Our team will be in touch shortly.",
    link: '/seller-dashboard/inquiries#inq_s1',
    isRead: true,
    type: 'engagement'
  }
];
