
import type { Listing, User, AdminDashboardMetrics, VerificationRequestItem, ReadyToEngageItem, Inquiry, NotificationItem, ListingStatus } from './types';
import { BuyerPersonaTypes, PreferredInvestmentSizes, industries, asianCountries, revenueRanges, profitMarginRanges, dealStructures, employeeCountRanges, placeholderKeywords } from './types';


export const sampleUsers: User[] = [
  {
    id: 'user1',
    fullName: 'John Doe (Seller)',
    email: 'john.seller@example.com',
    phoneNumber: '+6591234567',
    country: 'Singapore',
    role: 'seller',
    isEmailVerified: true,
    verificationStatus: 'verified',
    isPaid: true,
    initialCompanyName: 'JD Web Solutions Pte Ltd',
    createdAt: new Date('2023-01-10T09:00:00Z'),
    updatedAt: new Date('2023-01-15T14:30:00Z'),
    lastLogin: new Date('2024-05-20T10:00:00Z'),
    listingCount: 2,
  },
  {
    id: 'user2',
    fullName: 'Jane Smith (Buyer)',
    email: 'jane.buyer@example.com',
    phoneNumber: '+60123456789',
    country: 'Malaysia',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'verified',
    isPaid: true,
    buyerPersonaType: BuyerPersonaTypes[0],
    investmentFocusDescription: "Early-stage SaaS and e-commerce businesses in Southeast Asia with strong growth potential.",
    preferredInvestmentSize: PreferredInvestmentSizes[1],
    keyIndustriesOfInterest: "Technology, E-commerce, Fintech",
    createdAt: new Date('2023-02-05T11:00:00Z'),
    updatedAt: new Date('2023-02-05T11:00:00Z'),
    lastLogin: new Date('2024-05-21T11:00:00Z'),
    inquiryCount: 3,
  },
  {
    id: 'user3',
    fullName: 'Alex Tan (Seller - Anonymous)',
    email: 'alex.seller.anon@example.com',
    phoneNumber: '+84987654321',
    country: 'Vietnam',
    role: 'seller',
    isEmailVerified: true,
    verificationStatus: 'anonymous',
    isPaid: false,
    initialCompanyName: 'Anonymous SaaS Co.',
    createdAt: new Date('2023-03-20T16:00:00Z'),
    updatedAt: new Date('2023-03-20T16:00:00Z'),
    lastLogin: new Date('2024-05-19T09:00:00Z'),
    listingCount: 1,
  },
   {
    id: 'user4',
    fullName: 'Sarah Chen (Buyer - Pending)',
    email: 'sarah.buyer.pending@example.com',
    phoneNumber: '+1234567890',
    country: 'Thailand',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'pending_verification',
    isPaid: false,
    buyerPersonaType: BuyerPersonaTypes[1],
    investmentFocusDescription: "Mid-market companies in consumer goods and services with established revenue streams. Looking for majority stakes.",
    preferredInvestmentSize: PreferredInvestmentSizes[3],
    keyIndustriesOfInterest: "Retail, Consumer Goods, Hospitality",
    createdAt: new Date('2023-04-10T10:00:00Z'),
    updatedAt: new Date('2023-04-10T10:00:00Z'),
    lastLogin: new Date('2024-05-18T14:00:00Z'),
    inquiryCount: 0,
  },
  {
    id: 'user5',
    fullName: 'Michael Lee (Buyer - Free)',
    email: 'michael.freebuyer@example.com',
    phoneNumber: '+6281234567890',
    country: 'Indonesia',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'verified',
    isPaid: false,
    buyerPersonaType: BuyerPersonaTypes[2],
    investmentFocusDescription: "Acquiring businesses to integrate into our existing portfolio, primarily in logistics and supply chain.",
    preferredInvestmentSize: PreferredInvestmentSizes[2],
    keyIndustriesOfInterest: "Logistics, Supply Chain, Software",
    createdAt: new Date('2023-05-01T11:00:00Z'),
    updatedAt: new Date('2023-05-01T11:00:00Z'),
    lastLogin: new Date('2024-05-20T17:00:00Z'),
    inquiryCount: 1,
  },
  {
    id: 'user6',
    fullName: 'Anna Tay (Buyer - Anonymous)',
    email: 'anna.buyer.anon@example.com',
    phoneNumber: '+639171234567',
    country: 'Philippines',
    role: 'buyer',
    isEmailVerified: true,
    verificationStatus: 'anonymous',
    isPaid: false,
    buyerPersonaType: BuyerPersonaTypes[0],
    investmentFocusDescription: "Looking for small, profitable online businesses to operate and grow.",
    preferredInvestmentSize: PreferredInvestmentSizes[0],
    keyIndustriesOfInterest: "E-commerce, Content Websites",
    createdAt: new Date('2023-06-15T09:00:00Z'),
    updatedAt: new Date('2023-06-15T09:00:00Z'),
    lastLogin: new Date('2024-05-17T10:00:00Z'),
    inquiryCount: 1,
  },
];

export const sampleListings: Listing[] = [
  {
    id: '1',
    sellerId: 'user1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    industry: 'E-commerce',
    locationCountry: 'Singapore',
    locationCityRegionGeneral: 'Nationwide',
    anonymousBusinessDescription: 'Thriving online retail business with a strong brand presence and loyal customer base. Specializes in eco-friendly products. Consistent growth year-over-year.',
    keyStrengthsAnonymous: ['Strong Brand Recognition', 'High Customer Retention', 'Scalable Operations'],
    annualRevenueRange: '$500K - $1M USD',
    netProfitMarginRange: '20% - 30%',
    askingPrice: 1500000,
    adjustedCashFlow: 220000,
    adjustedCashFlowExplanation: "Adjusted for owner's discretionary expenses and one-time setup costs from last year.",
    dealStructureLookingFor: ['Full Acquisition'],
    reasonForSellingAnonymous: 'Owner retiring.',
    status: 'verified_public',
    isSellerVerified: true,
    actualCompanyName: 'GreenEarth Goods Pte. Ltd.',
    registeredBusinessName: 'GreenEarth Goods Pte. Ltd.',
    businessModel: "Direct-to-Consumer (DTC) E-commerce",
    yearEstablished: 2018,
    businessWebsiteUrl: 'https://greenearth.example.com',
    socialMediaLinks: "https://facebook.com/greenearth\nhttps://instagram.com/greenearth",
    numberOfEmployees: "6-10",
    technologyStack: "Shopify Plus, Klaviyo, Gorgias, Custom Inventory Management",
    fullBusinessAddress: '123 Orchard Road, Singapore',
    specificAnnualRevenueLastYear: 750000,
    specificNetProfitLastYear: 180000,
    detailedReasonForSelling: "Owner wishes to retire after successfully building and scaling the business over the past 5 years. Looking for a passionate successor.",
    sellerRoleAndTimeCommitment: "Owner currently spends ~20 hours/week on strategic oversight, supplier relations, and new product development. Day-to-day operations managed by a small team.",
    postSaleTransitionSupport: "Willing to offer 3-6 months of transition support and training to ensure a smooth handover.",
    specificGrowthOpportunities: "- Expand to Malaysia and Indonesia markets.\n- Launch a subscription box service for core products.\n- Invest in paid social media advertising campaigns.",
    createdAt: new Date('2023-10-15T10:00:00Z'),
    updatedAt: new Date('2023-10-15T10:00:00Z'),
    imageUrls: [
        'https://placehold.co/800x600.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png',
        'https://placehold.co/600x400.png'
    ],
    financialDocumentsUrl: '/documents/placeholder-financials.pdf',
    keyMetricsReportUrl: '/documents/placeholder-metrics.pdf',
    ownershipDocumentsUrl: '/documents/placeholder-ownership.pdf',
    secureDataRoomLink: 'https://example-dataroom.com/listing1',
    financialSnapshotUrl: '/documents/placeholder-financials-snapshot.pdf',
    ownershipDetailsUrl: '/documents/placeholder-ownership-details.pdf',
    locationRealEstateInfoUrl: '/documents/placeholder-lease-agreement.pdf',
    webPresenceInfoUrl: '/documents/placeholder-web-analytics-report.pdf',
    inquiryCount: 5,
  },
  {
    id: '2',
    sellerId: 'user3',
    listingTitleAnonymous: 'Established SaaS Platform - B2B Niche',
    industry: 'Software',
    locationCountry: 'Vietnam',
    locationCityRegionGeneral: 'Ho Chi Minh City Area',
    anonymousBusinessDescription: 'Innovative SaaS solution catering to a specific B2B vertical. Growing subscriber base with high MRR. Lean operations, ready for scaling with marketing investment. Solid tech stack.',
    keyStrengthsAnonymous: ['Unique Market Position', 'Recurring Revenue Model', 'High Growth Potential'],
    annualRevenueRange: '$100K - $250K USD',
    askingPrice: 350000,
    adjustedCashFlow: 90000,
    adjustedCashFlowExplanation: "SDE (Seller's Discretionary Earnings) after normalizing owner's salary.",
    dealStructureLookingFor: ['Full Acquisition', 'Partial Sale/Investment'],
    status: 'active',
    isSellerVerified: false,
    businessModel: "Subscription-based SaaS",
    yearEstablished: 2020,
    registeredBusinessName: "VN Tech Solutions Co. Ltd.",
    specificGrowthOpportunities: "- Develop enterprise-tier features.\n- Expand sales team for direct outreach in APAC.\n- Integrate with complementary services X and Y.",
    createdAt: new Date('2023-11-01T14:30:00Z'),
    updatedAt: new Date('2023-11-01T14:30:00Z'),
    imageUrls: ['https://placehold.co/800x600.png'],
    inquiryCount: 2,
  },
  {
    id: '3',
    sellerId: 'user1',
    listingTitleAnonymous: 'Boutique Marketing Agency',
    industry: 'Services - Marketing',
    locationCountry: 'Malaysia',
    locationCityRegionGeneral: 'Kuala Lumpur',
    anonymousBusinessDescription: 'Creative marketing agency with a portfolio of SME clients. Specializes in digital marketing and content creation. Strong local reputation. Team of 5 experienced professionals.',
    keyStrengthsAnonymous: ['Strong Client Relationships', 'Creative Team', 'Diverse Service Offering'],
    annualRevenueRange: '$250K - $500K USD',
    netProfitMarginRange: '10% - 20%',
    askingPrice: 700000,
    status: 'verified_public',
    isSellerVerified: true,
    actualCompanyName: 'Creative Spark Solutions Sdn. Bhd.',
    registeredBusinessName: 'Creative Spark Solutions Sdn. Bhd.',
    businessModel: "Service-based Agency",
    yearEstablished: 2019,
    numberOfEmployees: "1-5",
    specificGrowthOpportunities: "- Target larger corporate clients.\n- Develop proprietary marketing software/tools.\n- Expand service offerings to include PR and event management.",
    createdAt: new Date('2023-09-20T08:00:00Z'),
    updatedAt: new Date('2023-09-20T08:00:00Z'),
    imageUrls: ['https://placehold.co/800x600.png', 'https://placehold.co/600x400.png'],
    financialSnapshotUrl: '/documents/placeholder-agency-financials.pdf',
    webPresenceInfoUrl: 'https://example-agency.com',
    inquiryCount: 1,
  },
   {
    id: '4',
    sellerId: 'user3',
    listingTitleAnonymous: 'Modern Cafe in Tourist Hotspot',
    industry: 'Retail',
    locationCountry: 'Thailand',
    locationCityRegionGeneral: 'Phuket',
    anonymousBusinessDescription: 'Popular cafe with excellent reviews and high foot traffic. Known for specialty coffee and unique menu. Turnkey operation with trained staff. Strong social media presence.',
    keyStrengthsAnonymous: ['Prime Location', 'Established Reputation', 'Loyal Customer Base', 'High Online Ratings'],
    annualRevenueRange: '$100K - $250K USD',
    netProfitMarginRange: '15% - 25%',
    askingPrice: 220000,
    adjustedCashFlow: 65000,
    status: 'pending_verification',
    isSellerVerified: false,
    businessModel: "Brick-and-mortar retail cafe",
    yearEstablished: 2021,
    createdAt: new Date('2023-12-01T09:00:00Z'),
    updatedAt: new Date('2023-12-01T09:00:00Z'),
    imageUrls: ['https://placehold.co/800x600.png'],
    inquiryCount: 0,
  },
];

export const sampleBuyerInquiries: Inquiry[] = [
  {
    id: 'inq_b1',
    listingId: '1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user2',
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    inquiryTimestamp: new Date('2023-11-10T10:00:00Z'),
    sellerStatus: 'Platform Verified Seller',
    status: 'ready_for_admin_connection',
    statusBuyerPerspective: 'Ready for Admin Connection',
    createdAt: new Date('2023-11-10T10:00:00Z'),
    updatedAt: new Date('2023-11-11T10:00:00Z'),
  },
  {
    id: 'inq_b2',
    listingId: '2',
    listingTitleAnonymous: 'Established SaaS Platform - B2B Niche',
    sellerId: 'user3',
    buyerId: 'user2',
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    inquiryTimestamp: new Date('2023-11-08T15:30:00Z'),
    sellerStatus: 'Anonymous Seller',
    status: 'seller_engaged_seller_pending_verification',
    statusBuyerPerspective: 'Seller Engaged - Seller Verification Pending',
    createdAt: new Date('2023-11-08T15:30:00Z'),
    updatedAt: new Date('2023-11-08T15:30:00Z'),
  },
  {
    id: 'inq_b3',
    listingId: '1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user6',
    buyerName: 'Anna Tay (Buyer - Anonymous)',
    buyerVerificationStatus: 'anonymous',
    inquiryTimestamp: new Date('2023-11-12T09:00:00Z'),
    sellerStatus: 'Platform Verified Seller',
    status: 'seller_engaged_buyer_pending_verification',
    statusBuyerPerspective: 'Seller Engaged - Your Verification Required',
    createdAt: new Date('2023-11-12T09:00:00Z'),
    updatedAt: new Date('2023-11-12T10:00:00Z'),
  },
];

export const sampleSellerInquiries: Inquiry[] = [
  {
    id: 'inq_s1',
    listingId: '1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user2',
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    inquiryTimestamp: new Date('2023-11-10T10:00:00Z'),
    status: 'ready_for_admin_connection',
    statusSellerPerspective: 'Ready for Admin Connection',
    createdAt: new Date('2023-11-10T10:00:00Z'),
    updatedAt: new Date('2023-11-11T10:00:00Z'),
    engagementTimestamp: new Date('2023-11-11T09:00:00Z'),
  },
  {
    id: 'inq_s2',
    listingId: '1',
    listingTitleAnonymous: 'Profitable E-commerce Store in SEA',
    sellerId: 'user1',
    buyerId: 'user6',
    buyerName: 'Anna Tay (Buyer - Anonymous)',
    buyerVerificationStatus: 'anonymous',
    inquiryTimestamp: new Date('2023-11-12T09:00:00Z'),
    status: 'new_inquiry',
    statusSellerPerspective: 'New Inquiry',
    createdAt: new Date('2023-11-12T09:00:00Z'),
    updatedAt: new Date('2023-11-12T09:00:00Z'),
  },
   {
    id: 'inq_s3',
    listingId: '2',
    listingTitleAnonymous: 'Established SaaS Platform - B2B Niche',
    sellerId: 'user3',
    buyerId: 'user2',
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    inquiryTimestamp: new Date('2023-11-08T15:30:00Z'),
    status: 'seller_engaged_seller_pending_verification',
    statusSellerPerspective: 'You Engaged - Your Listing Verification Pending',
    createdAt: new Date('2023-11-08T15:30:00Z'),
    updatedAt: new Date('2023-11-09T15:30:00Z'),
    engagementTimestamp: new Date('2023-11-09T15:30:00Z'),
  },
];


const revenueFromBuyersPlaceholder = 5600;
const revenueFromSellersPlaceholder = 7850;
const activeSuccessfulConnectionsPlaceholder = 8;
const closedSuccessfulConnectionsPlaceholder = 4;

export const sampleAdminDashboardMetrics: AdminDashboardMetrics = {
  newUserRegistrations24hSellers: 2,
  newUserRegistrations24hBuyers: 3,
  newUserRegistrations7dSellers: 10,
  newUserRegistrations7dBuyers: 13,
  newListingsCreated24h: 2,
  newListingsCreated7d: 10,
  totalActiveSellers: sampleUsers.filter(u => u.role === 'seller').length,
  totalPaidSellers: sampleUsers.filter(u => u.role === 'seller' && u.isPaid).length,
  totalFreeSellers: sampleUsers.filter(u => u.role === 'seller' && !u.isPaid).length,
  totalActiveBuyers: sampleUsers.filter(u => u.role === 'buyer').length,
  totalPaidBuyers: sampleUsers.filter(u => u.role === 'buyer' && u.isPaid).length,
  totalFreeBuyers: sampleUsers.filter(u => u.role === 'buyer' && !u.isPaid).length,
  totalActiveListingsAnonymous: sampleListings.filter(l => (l.status === 'active' || l.status === 'verified_anonymous')).length,
  totalActiveListingsVerified: sampleListings.filter(l => l.status === 'verified_public').length,
  totalListingsAllStatuses: sampleListings.length,
  closedOrDeactivatedListings: sampleListings.filter(l => l.status === 'inactive' || l.status === 'closed_deal').length,
  buyerVerificationQueueCount: sampleUsers.filter(u => u.role === 'buyer' && u.verificationStatus === 'pending_verification').length,
  sellerVerificationQueueCount: sampleUsers.filter(u => u.role === 'seller' && u.verificationStatus === 'pending_verification').length + sampleListings.filter(l => l.status === 'pending_verification').length,
  readyToEngageQueueCount: sampleSellerInquiries.filter(i => i.status === 'ready_for_admin_connection').length,
  successfulConnectionsMTD: activeSuccessfulConnectionsPlaceholder + closedSuccessfulConnectionsPlaceholder,
  activeSuccessfulConnections: activeSuccessfulConnectionsPlaceholder,
  closedSuccessfulConnections: closedSuccessfulConnectionsPlaceholder,
  dealsClosedMTD: closedSuccessfulConnectionsPlaceholder,
  revenueFromBuyers: revenueFromBuyersPlaceholder,
  revenueFromSellers: revenueFromSellersPlaceholder,
  totalRevenueMTD: revenueFromBuyersPlaceholder + revenueFromSellersPlaceholder,
};

export const sampleVerificationRequests: VerificationRequestItem[] = [
  {
    id: 'vr1',
    timestamp: new Date('2023-11-10T10:00:00Z'),
    userId: 'user4',
    userName: 'Sarah Chen (Buyer - Pending)',
    userRole: 'buyer',
    reason: 'New buyer registration, requires profile verification.',
    status: 'New Request',
    documentsSubmitted: [{name: 'ID_Proof_Sarah.pdf', type: 'id_proof'}]
  },
  {
    id: 'vr2',
    timestamp: new Date('2023-11-09T15:30:00Z'),
    userId: 'user3',
    userName: 'Alex Tan (Seller - Anonymous)',
    userRole: 'seller',
    listingId: '2',
    listingTitle: 'Established SaaS Platform - B2B Niche',
    reason: 'Seller submitted new listing, requires seller and listing verification.',
    status: 'Contacted',
    documentsSubmitted: [{name: 'BusinessReg_Alex.pdf', type: 'business_reg'}]
  },
  {
    id: 'vr3',
    timestamp: new Date('2023-11-11T11:00:00Z'),
    userId: 'user5',
    userName: 'Michael Lee (Buyer - Free)',
    userRole: 'buyer',
    reason: 'Buyer requested manual verification upgrade.',
    status: 'Docs Under Review',
  },
   {
    id: 'vr4',
    timestamp: new Date('2023-11-12T09:00:00Z'),
    userId: 'user1',
    userName: 'John Doe (Seller)',
    userRole: 'seller',
    reason: 'Seller requested profile re-verification after significant update.',
    listingId: undefined,
    listingTitle: undefined,
    status: 'New Request',
  },
];

export const sampleReadyToEngageItems: ReadyToEngageItem[] = [
  {
    id: 'rte1',
    timestamp: new Date('2023-11-11T10:00:00Z'),
    buyerId: 'user2',
    buyerName: 'Jane Smith (Buyer)',
    buyerVerificationStatus: 'verified',
    sellerId: 'user1',
    sellerName: 'John Doe (Seller)',
    sellerVerificationStatus: 'verified',
    listingId: '1',
    listingTitle: 'Profitable E-commerce Store in SEA',
    listingVerificationStatus: 'verified_public'
  },
];

export const sampleBuyerNotifications: NotificationItem[] = [
  {
    id: 'notif1_buyer2',
    userId: 'user2',
    timestamp: new Date('2023-11-11T10:05:00Z'),
    message: "Great news! Both you and the Seller for listing 'Profitable E-commerce Store in SEA' are verified and have agreed to engage. Our team will be in touch shortly.",
    link: '/dashboard/inquiries#inq_b1',
    isRead: false,
    type: 'engagement'
  },
  {
    id: 'notif2_buyer6',
    userId: 'user6',
    timestamp: new Date('2023-11-12T10:05:00Z'),
    message: "The seller of 'Profitable E-commerce Store in SEA' is ready to engage! To proceed, your profile needs to be verified.",
    link: '/dashboard/verification',
    isRead: false,
    type: 'verification'
  },
  {
    id: 'notif3_buyer2',
    userId: 'user2',
    timestamp: new Date('2023-11-09T08:00:00Z'),
    message: "Your profile information was successfully updated.",
    isRead: true,
    type: 'system'
  }
];

export const sampleSellerNotifications: NotificationItem[] = [
  {
    id: 'notif1_seller1',
    userId: 'user1',
    timestamp: new Date('2023-11-12T09:05:00Z'),
    message: "You have a new inquiry for your listing 'Profitable E-commerce Store in SEA' from Anna Tay (Buyer - Anonymous).",
    link: '/seller-dashboard/inquiries#inq_s2',
    isRead: false,
    type: 'inquiry'
  },
  {
    id: 'notif2_seller3',
    userId: 'user3',
    timestamp: new Date('2023-11-13T11:00:00Z'),
    message: "You've chosen to engage with Jane Smith regarding 'Established SaaS Platform - B2B Niche'. To proceed, your listing needs to be verified.",
    link: '/seller-dashboard/verification?listingId=2',
    isRead: false,
    type: 'verification'
  },
  {
    id: 'notif3_seller1',
    userId: 'user1',
    timestamp: new Date('2023-11-11T10:05:00Z'),
    message: "Great news! Both you and Jane Smith (Buyer) for listing 'Profitable E-commerce Store in SEA' are verified and have agreed to engage. Our team will be in touch shortly.",
    link: '/seller-dashboard/inquiries#inq_s1',
    isRead: true,
    type: 'engagement' // Corrected the unterminated string here
  }
];
