// Sample listings generated from Seller_Tracker_Full_Profiles.csv
// Auto-generated — do not edit manually

export const sampleListings = [
  {
    id: 'listing-001',
    listing_title_anonymous: `Profitable Japanese-inspired fashion brand`,
    anonymous_business_description: `This Bandung-based Indonesian fashion brand, founded in 2008, specializes in Japanese-inspired dailywear, streetwear, and sportswear. The product catalog spans t-shirts, polo shirts, sweaters, shirts, denim, jackets, joggers, dresses, and boxer shorts for men, women, and children. The brand also offers accessories including bags, hats, and gaming thumb gloves. All products are made using premium materials such as 100% cotton, and the company employs experienced tailors with strict quality standards.

The brand operates an official e-commerce website built on Shopify, sells through major Indonesian marketplaces like Shopee and Tokopedia, and has expanded internationally to Shopee Mall in Singapore, Malaysia, and the Philippines. It offers same-day shipping within Indonesia via J&T Express and international shipping through DHL. With over 114,000 Instagram followers and a physical store in Padalarang, West Java, the brand has built a growing base of loyal repeat customers who value its combination of simple, modern Japanese-inspired design and affordable pricing.`,
    asking_price: 20650000,
    industry: 'Retail & E-commerce',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_0.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
    seller_id: 'sample-seller-001',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 5900000,
    ebitda: 4130000,
    key_strength_1: `Strong Japanese-inspired design identity with simple, modern, and casual aesthetics that differentiate the brand in Indonesia's competitive local fashion market.`,
    key_strength_2: `Comprehensive product range for men, women, and children, including unique niche accessories like gaming thumb gloves, giving the brand broad market appeal.`,
    key_strength_3: `Use of premium materials (100% cotton fabrics), experienced craftsmanship, and same-day domestic shipping with a 100% satisfaction guarantee, reinforcing trust and quality.`,
    growth_opportunity_1: `Further international expansion beyond Southeast Asian Shopee Mall presence into additional global e-commerce platforms and markets.`,
    growth_opportunity_2: `Development of the brand's recently launched fragrance line to diversify revenue streams beyond apparel.`,
    growth_opportunity_3: `Scaling the reseller and affiliate program to increase distribution reach across Indonesia's diverse regions and tap into social commerce trends.`,
    key_strengths_anonymous: [`Strong Japanese-inspired design identity with simple, modern, and casual aesthetics that differentiate the brand in Indonesia's competitive local fashion market.`, `Comprehensive product range for men, women, and children, including unique niche accessories like gaming thumb gloves, giving the brand broad market appeal.`, `Use of premium materials (100% cotton fabrics), experienced craftsmanship, and same-day domestic shipping with a 100% satisfaction guarantee, reinforcing trust and quality.`],
    specific_growth_opportunities: `• Further international expansion beyond Southeast Asian Shopee Mall presence into additional global e-commerce platforms and markets.
• Development of the brand's recently launched fragrance line to diversify revenue streams beyond apparel.
• Scaling the reseller and affiliate program to increase distribution reach across Indonesia's diverse regions and tap into social commerce trends.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-002',
    listing_title_anonymous: `High-revenue SME super-app`,
    anonymous_business_description: `This Indonesian technology company provides a comprehensive digital super-app platform designed to empower micro, small, and medium enterprises (UMKM). Originally launched as M-PULSA on Android in 2018, the platform was rebranded in 2022. It offers a wide suite of services including digital product sales (mobile credit, data packages, PLN electricity tokens, game vouchers), QRIS digital payment solutions, a free point-of-sale cashier system, e-grocery supply chain connections to distributors, multi-courier logistics, social commerce features, mini ATM services, and access to Kredit Usaha Rakyat (KUR) microfinance.

The platform has been downloaded and used by over 900,000 users spread across Indonesia, serving as a one-stop business solution for traditional shop owners, online sellers, and small businesses. It holds ISO certifications for quality management and information security management (ISMS). The company is headquartered in Bangkalan, East Java, and partners with major Indonesian banks for payment processing. Customer service operates 24/7, and the app is available on both Android and iOS platforms.`,
    asking_price: 312900000,
    industry: 'Information Technology (IT)',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_1.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-11T08:00:00Z',
    updated_at: '2026-03-11T10:00:00Z',
    seller_id: 'sample-seller-002',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 89400000,
    ebitda: 62580000,
    key_strength_1: `All-in-one super-app ecosystem combining digital product reselling, QRIS payments, POS cashier, e-grocery supply chain, logistics, and microfinance into a single platform for UMKM.`,
    key_strength_2: `Massive nationwide user base of over 900,000 active users, creating strong network effects and economies of scale across Indonesia's small business sector.`,
    key_strength_3: `ISO-certified quality management and information security standards, combined with 24/7 customer service and partnerships with major banks.`,
    growth_opportunity_1: `Deepening the e-grocery and FMCG supply chain feature to further connect small retailers directly with distributors.`,
    growth_opportunity_2: `Expanding social commerce capabilities to help UMKM leverage digital marketing and reach broader consumer audiences.`,
    growth_opportunity_3: `Scaling KUR microfinance access and financial services to become a more comprehensive fintech solution for underserved small businesses across rural Indonesia.`,
    key_strengths_anonymous: [`All-in-one super-app ecosystem combining digital product reselling, QRIS payments, POS cashier, e-grocery supply chain, logistics, and microfinance into a single platform for UMKM.`, `Massive nationwide user base of over 900,000 active users, creating strong network effects and economies of scale across Indonesia's small business sector.`, `ISO-certified quality management and information security standards, combined with 24/7 customer service and partnerships with major banks.`],
    specific_growth_opportunities: `• Deepening the e-grocery and FMCG supply chain feature to further connect small retailers directly with distributors.
• Expanding social commerce capabilities to help UMKM leverage digital marketing and reach broader consumer audiences.
• Scaling KUR microfinance access and financial services to become a more comprehensive fintech solution for underserved small businesses across rural Indonesia.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-003',
    listing_title_anonymous: `Global teak furniture exporter`,
    anonymous_business_description: `This premier Indonesian teak wood furniture manufacturer is headquartered in Jepara, Central Java, widely regarded as the epicenter of fine teak furniture production. With over 40 years of experience, the company blends traditional Jepara craftsmanship with modern European design principles, managed by a professional European management team. The factory employs world-class local carpenters who implement European production techniques, achieving a damage rate below 1%. Product categories include bedroom furniture, living room pieces, dining furniture, and custom designs.

The company exports to over 20 countries across 5 continents, with primary markets in the USA, Taiwan, and France. It serves wholesale distributors, physical and online retailers, and provides bespoke furniture solutions for upscale hotels, resorts, restaurants, and private residences. The company carries the 100% Indonesian Legal Wood certification, ensuring all teak is sourced from controlled, replanted areas committed to combating deforestation.`,
    asking_price: 10500000,
    industry: 'Manufacturing & Production',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_2.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-12T08:00:00Z',
    updated_at: '2026-03-12T10:00:00Z',
    seller_id: 'sample-seller-003',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 3000000,
    ebitda: 2100000,
    key_strength_1: `Over 40 years of manufacturing expertise in Jepara with world-class carpenters, European management oversight, and a sub-1% damage rate.`,
    key_strength_2: `100% Indonesian Legal Wood certification with commitment to sustainable sourcing and ethical working conditions.`,
    key_strength_3: `Established global export network spanning 5 continents and 20+ countries, serving diverse channels from wholesale to luxury hospitality projects.`,
    growth_opportunity_1: `Expanding direct-to-consumer online retail channels globally to capture higher margins beyond traditional wholesale distribution.`,
    growth_opportunity_2: `Developing outdoor furniture and complementary home decor product lines to broaden the catalog.`,
    growth_opportunity_3: `Strengthening brand presence at additional international trade shows and digital marketing to penetrate emerging markets.`,
    key_strengths_anonymous: [`Over 40 years of manufacturing expertise in Jepara with world-class carpenters, European management oversight, and a sub-1% damage rate.`, `100% Indonesian Legal Wood certification with commitment to sustainable sourcing and ethical working conditions.`, `Established global export network spanning 5 continents and 20+ countries, serving diverse channels from wholesale to luxury hospitality projects.`],
    specific_growth_opportunities: `• Expanding direct-to-consumer online retail channels globally to capture higher margins beyond traditional wholesale distribution.
• Developing outdoor furniture and complementary home decor product lines to broaden the catalog.
• Strengthening brand presence at additional international trade shows and digital marketing to penetrate emerging markets.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-004',
    listing_title_anonymous: `Award-winning healthy snack producer`,
    anonymous_business_description: `This whole food nutrition company was founded in June 2021 during the COVID-19 lockdown in Bali, when a group of friends began making homemade beef jerky as a healthy snack. The venture grew rapidly, evolving into a full product line that includes beef chips, beef jerky, chicken chips, banana crunch snacks, and superfood supplements such as freeze-dried grass-fed beef organs, beef liver, and beef collagen and marrow capsules. All beef is sourced from grass-fed, grass-finished cows raised by smallholder farmers on Bali's volcanic highlands using sustainable agriculture practices, with no hormones, antibiotics, or GMOs.

The company is HALAL and BPOM certified, and won the prestigious Snack Food Innovation award at Food&Hotel Asia (FHA) in Singapore. Products are available through the company's online store with nationwide shipping across Indonesia, as well as through dozens of physical retail stockists in Bali, Jakarta, and other major cities. The brand caters to various dietary preferences including keto, carnivore, and gluten-free lifestyles.`,
    asking_price: 2513000,
    industry: 'Manufacturing & Production',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_3.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-13T08:00:00Z',
    updated_at: '2026-03-13T10:00:00Z',
    seller_id: 'sample-seller-004',
    annual_revenue_range: '$500K - $1M USD',
    specific_annual_revenue_last_year: 718000,
    ebitda: 502600,
    key_strength_1: `Award-winning products (FHA Snack Food Innovation award) made from traceable, grass-fed, non-GMO ingredients sourced directly from Bali's smallholder farmers.`,
    key_strength_2: `HALAL and BPOM certifications, appealing to health-conscious consumers across diverse dietary preferences.`,
    key_strength_3: `Extensive retail distribution network across Bali and Jakarta through premium grocery stores, wellness cafes, and fitness clubs.`,
    growth_opportunity_1: `International expansion into health food markets in Southeast Asia, Australia, and beyond, leveraging the FHA award recognition.`,
    growth_opportunity_2: `Broadening the superfood supplement line to tap into the rapidly growing global market for whole food, bioavailable nutrient supplements.`,
    growth_opportunity_3: `Developing partnerships with gyms, wellness retreats, and subscription box services to create recurring revenue streams.`,
    key_strengths_anonymous: [`Award-winning products (FHA Snack Food Innovation award) made from traceable, grass-fed, non-GMO ingredients sourced directly from Bali's smallholder farmers.`, `HALAL and BPOM certifications, appealing to health-conscious consumers across diverse dietary preferences.`, `Extensive retail distribution network across Bali and Jakarta through premium grocery stores, wellness cafes, and fitness clubs.`],
    specific_growth_opportunities: `• International expansion into health food markets in Southeast Asia, Australia, and beyond, leveraging the FHA award recognition.
• Broadening the superfood supplement line to tap into the rapidly growing global market for whole food, bioavailable nutrient supplements.
• Developing partnerships with gyms, wellness retreats, and subscription box services to create recurring revenue streams.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-005',
    listing_title_anonymous: `Pre-revenue esports community platform`,
    anonymous_business_description: `This Indonesian esports and gaming community platform positions itself as the largest community platform for the gaming ecosystem in Indonesia. The company connects hundreds of gaming communities through its web-based platform, which features event organization and tournament infrastructure, editorial articles, leaderboards, a digital shop, and a community explorer tool. The platform has amassed over 500,000 active members and has hosted more than 1,000 online and offline esports and gaming community events.

Founded by Iskandar Ramli and Jaime Djuhar, the company partners with major industry players including Riot Games, Razer Gold, and Noctua for event production, broadcasting, and community engagement. The platform also extends into ACG (Anime, Comic, Gaming) communities, including cosplay and trading card game groups. With active social media presence on TikTok, Instagram, YouTube, and Facebook Gaming, the company serves as both a media portal and a tournament infrastructure provider.`,
    asking_price: 90000,
    industry: 'Arts & Entertainment',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_4.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-14T08:00:00Z',
    updated_at: '2026-03-14T10:00:00Z',
    seller_id: 'sample-seller-005',
    annual_revenue_range: '$50K - $100K USD',
    specific_annual_revenue_last_year: 60000,
    ebitda: null,
    key_strength_1: `Largest gaming community platform in Indonesia with over 500,000 active members and 1,000+ organized events, creating a dominant network effect.`,
    key_strength_2: `Strategic partnerships with major global gaming companies such as Riot Games, Razer Gold, and Noctua.`,
    key_strength_3: `Multi-format platform combining tournament infrastructure, editorial content, community management, and a digital shop into a single hub.`,
    growth_opportunity_1: `Monetizing the large user base through premium features, in-platform advertising, brand sponsorships, and expanded e-commerce offerings.`,
    growth_opportunity_2: `Expanding into adjacent ACG communities such as cosplay and trading card games to broaden the audience.`,
    growth_opportunity_3: `Scaling regional and international tournament hosting to position the platform as a pan-Southeast Asian esports infrastructure provider.`,
    key_strengths_anonymous: [`Largest gaming community platform in Indonesia with over 500,000 active members and 1,000+ organized events, creating a dominant network effect.`, `Strategic partnerships with major global gaming companies such as Riot Games, Razer Gold, and Noctua.`, `Multi-format platform combining tournament infrastructure, editorial content, community management, and a digital shop into a single hub.`],
    specific_growth_opportunities: `• Monetizing the large user base through premium features, in-platform advertising, brand sponsorships, and expanded e-commerce offerings.
• Expanding into adjacent ACG communities such as cosplay and trading card games to broaden the audience.
• Scaling regional and international tournament hosting to position the platform as a pan-Southeast Asian esports infrastructure provider.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-006',
    listing_title_anonymous: `Award-winning Central Java distributor`,
    anonymous_business_description: `This is a fast-moving consumer goods distribution company headquartered in Juwana, Central Java, Indonesia, with over 40 years of experience. The company operates four branch offices in Semarang, Juwana, Blora, and Demak, covering an extensive distribution network across Central Java. It distributes products spanning personal care, baby care, skincare, cosmetics, and beverages.

The company partners with major principals such as PT Amerta Indah Otsuka (Pocari Sweat), PT Sinar Sosro, PT Multi Bintang Indonesia, PT PZ Cussons Indonesia, PT Eka Jaya International (Hanasui), and PT KAO Indonesia. With approximately 200 employees and 60 delivery vehicles, it maintains a minimum service level of 95%. The company has earned multiple industry awards, including The Best Gold Distributor from PT Amerta Indah Otsuka in 2022 and 2023.`,
    asking_price: 50050000,
    industry: 'Retail & E-commerce',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_5.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-15T08:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
    seller_id: 'sample-seller-006',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 14300000,
    ebitda: 10010000,
    key_strength_1: `Over four decades of experience in FMCG distribution across Central Java, with multiple gold and silver distributor awards from major principals.`,
    key_strength_2: `Comprehensive coverage through four branch offices and 60 delivery vehicles, maintaining a 95%+ service level.`,
    key_strength_3: `Trusted by major consumer goods companies including PT Amerta Indah Otsuka, PT PZ Cussons Indonesia, PT KAO Indonesia, and others.`,
    growth_opportunity_1: `Extending distribution coverage beyond Central Java into other regions of Indonesia.`,
    growth_opportunity_2: `Investment in CRM systems and digital tools to improve operational efficiency and customer engagement.`,
    growth_opportunity_3: `Onboarding additional principals and expanding into new FMCG categories such as health foods or organic products.`,
    key_strengths_anonymous: [`Over four decades of experience in FMCG distribution across Central Java, with multiple gold and silver distributor awards from major principals.`, `Comprehensive coverage through four branch offices and 60 delivery vehicles, maintaining a 95%+ service level.`, `Trusted by major consumer goods companies including PT Amerta Indah Otsuka, PT PZ Cussons Indonesia, PT KAO Indonesia, and others.`],
    specific_growth_opportunities: `• Extending distribution coverage beyond Central Java into other regions of Indonesia.
• Investment in CRM systems and digital tools to improve operational efficiency and customer engagement.
• Onboarding additional principals and expanding into new FMCG categories such as health foods or organic products.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-007',
    listing_title_anonymous: `Gaming PC retail specialist`,
    anonymous_business_description: `This Indonesian IT retail company specializes in gaming devices and high-end notebook PCs, established in 2009. Headquartered in West Jakarta, it serves as a one-stop IT solution provider for professionals, gamers, and content creators, offering both B2C and B2B sales. The company operates multiple business units including an e-retail platform, a service center, a tech media channel, and a creative agency, with showrooms in Jakarta, Yogyakarta, Bintaro, and Serpong.

The company provides consultancy-based pre-sales and after-sales services, differentiating itself from traditional retail stores by emphasizing expert guidance and premium customer experience. It partners with leading vendors such as Lenovo, MSI, Asus, and Acer as an authorized reseller and service center. It has also introduced preloved laptop programs and device rental services for events and corporate use. The brand PEMMZ has become well-known among Indonesian PC enthusiasts and gamers for its curated product selection and knowledgeable staff.`,
    asking_price: 5950000,
    industry: 'Retail & E-commerce',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_6.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-16T08:00:00Z',
    updated_at: '2026-03-16T10:00:00Z',
    seller_id: 'sample-seller-007',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 1700000,
    ebitda: 1190000,
    key_strength_1: `Recognized as a pioneer gaming and high-end PC specialist in Indonesia since 2009, with strong brand loyalty from enthusiasts.`,
    key_strength_2: `End-to-end offering spanning retail, service center, tech media, creative agency, and device maintenance under one umbrella.`,
    key_strength_3: `Official partnerships with Lenovo, MSI, Asus, and Acer as an authorized reseller and service center.`,
    growth_opportunity_1: `Growing the B2B segment to capture corporate IT procurement, studio setups, and enterprise system integration projects.`,
    growth_opportunity_2: `Scaling preloved laptop and device rental programs to appeal to budget-conscious consumers and corporate clients.`,
    growth_opportunity_3: `Opening additional showrooms and service centers in key Indonesian cities beyond Jakarta and Yogyakarta.`,
    key_strengths_anonymous: [`Recognized as a pioneer gaming and high-end PC specialist in Indonesia since 2009, with strong brand loyalty from enthusiasts.`, `End-to-end offering spanning retail, service center, tech media, creative agency, and device maintenance under one umbrella.`, `Official partnerships with Lenovo, MSI, Asus, and Acer as an authorized reseller and service center.`],
    specific_growth_opportunities: `• Growing the B2B segment to capture corporate IT procurement, studio setups, and enterprise system integration projects.
• Scaling preloved laptop and device rental programs to appeal to budget-conscious consumers and corporate clients.
• Opening additional showrooms and service centers in key Indonesian cities beyond Jakarta and Yogyakarta.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-008',
    listing_title_anonymous: `Google-partnered messaging provider`,
    anonymous_business_description: `This IT solutions company based in East Jakarta serves as an official Google Cloud Partner and Google Workspace Reseller. The company specializes in cloud-based productivity solutions, SMS and WhatsApp messaging services, web hosting, domain registration, and web-based software development. Its flagship products include Google Workspace deployment and a messaging platform for SMS blast, WhatsApp blast, and business messaging solutions integrated with major Indonesian telecom operators.

The company also holds status as an official WhatsApp Business Solution Provider (BSP) in Indonesia, enabling it to provide verified WhatsApp Business accounts for enterprise clients. Its services cater to a wide range of business communication needs, from promotional SMS and payment notifications to chatbot integration. The company operates as a CPaaS (Communications Platform as a Service) and SaaS provider.`,
    asking_price: 102000,
    industry: 'Information Technology (IT)',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_7.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-17T08:00:00Z',
    updated_at: '2026-03-17T10:00:00Z',
    seller_id: 'sample-seller-008',
    annual_revenue_range: '< $50K USD',
    specific_annual_revenue_last_year: 29000,
    ebitda: 20400,
    key_strength_1: `Authorized Google Cloud Partner, Google Workspace Reseller, and WhatsApp Business Solution Provider in Indonesia.`,
    key_strength_2: `Integrated suite of business communication tools including SMS Blast, WhatsApp Blast, chatbot services, domain registration, and web hosting.`,
    key_strength_3: `Partnered with major Indonesian telecom operators (Telkomsel, XL Axiata, Indosat Ooredoo Hutchison).`,
    growth_opportunity_1: `Integrating AI-driven chatbots and smart messaging analytics for enterprise clients.`,
    growth_opportunity_2: `Expanding Google Workspace adoption among Indonesia's large and underserved SME segment.`,
    growth_opportunity_3: `Broadening the CPaaS platform to include RCS, email automation, and social media messaging.`,
    key_strengths_anonymous: [`Authorized Google Cloud Partner, Google Workspace Reseller, and WhatsApp Business Solution Provider in Indonesia.`, `Integrated suite of business communication tools including SMS Blast, WhatsApp Blast, chatbot services, domain registration, and web hosting.`, `Partnered with major Indonesian telecom operators (Telkomsel, XL Axiata, Indosat Ooredoo Hutchison).`],
    specific_growth_opportunities: `• Integrating AI-driven chatbots and smart messaging analytics for enterprise clients.
• Expanding Google Workspace adoption among Indonesia's large and underserved SME segment.
• Broadening the CPaaS platform to include RCS, email automation, and social media messaging.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-009',
    listing_title_anonymous: `Fast-growing healthcare staffing platform`,
    anonymous_business_description: `This healthtech startup based in Jakarta operates as an on-demand healthcare workforce platform connecting healthcare workers with facilities and patients. Founded by a nurse and an engineer, the company provides vetted healthcare professionals including doctors, nurses, caregivers, babysitters, and physiotherapists to fill shift vacancies at hospitals, clinics, and labs. It also offers homecare management systems and end-to-end healthcare recruitment services.

The platform achieved 18x year-over-year revenue growth in 2023, deploying over 3,000 on-demand healthcare jobs. It was honored as one of the Top 10 HealthTech Innovations by the Ministry of Health of Indonesia. The company has participated in Accelerating Asia's investment program and Startup Studio Indonesia, and is currently seeking seed-round investment to expand its customer base and enter new markets.`,
    asking_price: 1505000,
    industry: 'Health & Wellness',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_8.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-18T08:00:00Z',
    updated_at: '2026-03-18T10:00:00Z',
    seller_id: 'sample-seller-009',
    annual_revenue_range: '$250K - $500K USD',
    specific_annual_revenue_last_year: 430000,
    ebitda: 301000,
    key_strength_1: `Achieved 18x revenue growth year-over-year in 2023 with over 3,000 on-demand jobs deployed.`,
    key_strength_2: `Named one of the Top 10 HealthTech Innovations by Indonesia's Ministry of Health.`,
    key_strength_3: `Comprehensive platform covering on-demand shifting, homecare management, and permanent headhunting services.`,
    growth_opportunity_1: `Scaling beyond Jakarta into other major Indonesian cities and rural areas.`,
    growth_opportunity_2: `Targeting the estimated $4.3 billion urban home healthcare service market in Indonesia.`,
    growth_opportunity_3: `Developing advanced workforce management and scheduling automation tools for larger institutional clients.`,
    key_strengths_anonymous: [`Achieved 18x revenue growth year-over-year in 2023 with over 3,000 on-demand jobs deployed.`, `Named one of the Top 10 HealthTech Innovations by Indonesia's Ministry of Health.`, `Comprehensive platform covering on-demand shifting, homecare management, and permanent headhunting services.`],
    specific_growth_opportunities: `• Scaling beyond Jakarta into other major Indonesian cities and rural areas.
• Targeting the estimated $4.3 billion urban home healthcare service market in Indonesia.
• Developing advanced workforce management and scheduling automation tools for larger institutional clients.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-010',
    listing_title_anonymous: `Multi-country education consultancy`,
    anonymous_business_description: `This professional higher education consulting center is headquartered in Johor Bahru, Malaysia, with offices in Korea and Indonesia (Jakarta and Medan). Founded in 2008, the company has over 15 years of experience providing free consultations and one-stop education services to students seeking to study overseas. It assists students with university applications, accommodation arrangements, travel planning, and student visa processing for institutions across Singapore, Switzerland, England, Ireland, Australia, the UK, the US, Canada, China, and Korea.

The company also serves as an advisory board member for reputable international schools, vocational schools, and tuition centers across Malaysia, Indonesia, Korea, Pakistan, Japan, the Philippines, and Thailand. It offers flexible learning options and language preparatory programs. The organization was awarded the International Prestige Brand Award 2023 and the GPA Entrepreneur Award.`,
    asking_price: 875000,
    industry: 'Education',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_9.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-19T08:00:00Z',
    updated_at: '2026-03-19T10:00:00Z',
    seller_id: 'sample-seller-010',
    annual_revenue_range: '$250K - $500K USD',
    specific_annual_revenue_last_year: 250000,
    ebitda: 175000,
    key_strength_1: `Operates consulting offices in Malaysia, Korea, and Indonesia, providing on-the-ground support across Asia.`,
    key_strength_2: `Received the International Prestige Brand Award 2023 and GPA Entrepreneur Award, affirming over 15 years of trusted service.`,
    key_strength_3: `Offers end-to-end support from course consultation and university applications to accommodation, travel, visa processing, and language programs.`,
    growth_opportunity_1: `Adding emerging study destinations like New Zealand, Germany, and the Nordic countries.`,
    growth_opportunity_2: `Growing flexible learning and online study offerings for working adults.`,
    growth_opportunity_3: `Scaling operations in Indonesia, the Philippines, and Thailand where growing middle-class populations drive demand.`,
    key_strengths_anonymous: [`Operates consulting offices in Malaysia, Korea, and Indonesia, providing on-the-ground support across Asia.`, `Received the International Prestige Brand Award 2023 and GPA Entrepreneur Award, affirming over 15 years of trusted service.`, `Offers end-to-end support from course consultation and university applications to accommodation, travel, visa processing, and language programs.`],
    specific_growth_opportunities: `• Adding emerging study destinations like New Zealand, Germany, and the Nordic countries.
• Growing flexible learning and online study offerings for working adults.
• Scaling operations in Indonesia, the Philippines, and Thailand where growing middle-class populations drive demand.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-011',
    listing_title_anonymous: `Jakarta-based web development firm`,
    anonymous_business_description: `This Jakarta-based IT solutions company offers a comprehensive range of digital services including web design, web development, product management, marketing, and graphic design. Supported by a professional team located in Central Jakarta, the firm partners with businesses to address all their information technology needs, from building basic websites to deploying full-scale e-commerce platforms.

The company provides tiered service packages ranging from a Basic plan for template-based professional websites to an Ultimate plan delivering premium e-commerce solutions with free domain, hosting, SSL encryption, marketplace integration, and priority support. Its portfolio showcases a diverse array of completed projects spanning mobile apps, web applications, and design work for clients across sectors such as education, food services, finance, travel, and community organizations.`,
    asking_price: 1026000,
    industry: 'Information Technology (IT)',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_10.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-20T08:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
    seller_id: 'sample-seller-011',
    annual_revenue_range: '$250K - $500K USD',
    specific_annual_revenue_last_year: 293000,
    ebitda: 205200,
    key_strength_1: `End-to-end IT solution covering web design, development, graphic design, product management, and digital marketing under one roof.`,
    key_strength_2: `Clearly structured, tiered pricing packages that serve a wide range of budgets.`,
    key_strength_3: `Diverse project portfolio with proven delivery across multiple industries including finance, education, retail, and travel.`,
    growth_opportunity_1: `Expanding into mobile app development and SaaS products to capture growing demand for digital transformation.`,
    growth_opportunity_2: `Developing recurring revenue streams through managed hosting, maintenance retainers, and digital marketing subscriptions.`,
    growth_opportunity_3: `Targeting international clients in Southeast Asia by leveraging competitive Indonesian labor costs.`,
    key_strengths_anonymous: [`End-to-end IT solution covering web design, development, graphic design, product management, and digital marketing under one roof.`, `Clearly structured, tiered pricing packages that serve a wide range of budgets.`, `Diverse project portfolio with proven delivery across multiple industries including finance, education, retail, and travel.`],
    specific_growth_opportunities: `• Expanding into mobile app development and SaaS products to capture growing demand for digital transformation.
• Developing recurring revenue streams through managed hosting, maintenance retainers, and digital marketing subscriptions.
• Targeting international clients in Southeast Asia by leveraging competitive Indonesian labor costs.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-012',
    listing_title_anonymous: `Affordable Indonesian hosting provider`,
    anonymous_business_description: `This Indonesian web hosting provider delivers affordable and reliable hosting, domain registration, and cloud infrastructure services. With over 11 years of experience, the company serves a broad client base of SMEs, bloggers, internet marketers, and enterprises, offering shared hosting plans alongside WordPress hosting, reseller hosting, cloud VPS, and email hosting solutions.

The company's infrastructure leverages Litespeed web servers, SSD and NVMe storage with triple replication, and high-frequency processors. It maintains data centers in Indonesia, Singapore, and the United States, providing a 99.9% uptime guarantee. Each hosting package includes free SSL certificates, and select plans come with free domain registration and premium WordPress themes. The firm also developed Ujione, a cloud-based online examination application.`,
    asking_price: 700000,
    industry: 'Information Technology (IT)',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_11.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-21T08:00:00Z',
    updated_at: '2026-03-21T10:00:00Z',
    seller_id: 'sample-seller-012',
    annual_revenue_range: '$100K - $250K USD',
    specific_annual_revenue_last_year: 200000,
    ebitda: 140000,
    key_strength_1: `High-performance hosting with Litespeed web servers, NVMe SSD storage, and 99.9% uptime guarantee across multiple data center locations.`,
    key_strength_2: `Competitively priced plans with generous inclusions such as free domains, SSL certificates, and premium WordPress themes.`,
    key_strength_3: `Comprehensive product ecosystem spanning shared hosting, WordPress hosting, cloud VPS, reseller hosting, email hosting, and an online exam platform.`,
    growth_opportunity_1: `Expanding cloud VPS and managed services to capture increasing demand from businesses migrating to cloud infrastructure.`,
    growth_opportunity_2: `Growing the Ujione online examination platform as a standalone SaaS product.`,
    growth_opportunity_3: `Strengthening the reseller hosting program and white-label solutions to build a larger partner network.`,
    key_strengths_anonymous: [`High-performance hosting with Litespeed web servers, NVMe SSD storage, and 99.9% uptime guarantee across multiple data center locations.`, `Competitively priced plans with generous inclusions such as free domains, SSL certificates, and premium WordPress themes.`, `Comprehensive product ecosystem spanning shared hosting, WordPress hosting, cloud VPS, reseller hosting, email hosting, and an online exam platform.`],
    specific_growth_opportunities: `• Expanding cloud VPS and managed services to capture increasing demand from businesses migrating to cloud infrastructure.
• Growing the Ujione online examination platform as a standalone SaaS product.
• Strengthening the reseller hosting program and white-label solutions to build a larger partner network.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-013',
    listing_title_anonymous: `Established workforce outsourcing firm`,
    anonymous_business_description: `This Semarang-based outsourcing company is a trusted workforce solutions provider with over 15 years of experience across multiple industries in Indonesia. Founded by professionals with backgrounds in HRD, banking, finance, construction, and property, the firm manages between 1,000 and 5,000 employees deployed to client organizations.

The company provides a wide range of services including outsourcing management, building management, security services, cleaning services, sales agency staffing, and training programs. Its client roster features prominent names such as Nestle, Danamon, CIMB, Telkomsel, Transmart, and Admedika. The firm handles the full lifecycle of workforce management, from recruitment and selection through training and payroll processing.`,
    asking_price: 1046000,
    industry: 'Consulting',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_12.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-22T08:00:00Z',
    updated_at: '2026-03-22T10:00:00Z',
    seller_id: 'sample-seller-013',
    annual_revenue_range: '$250K - $500K USD',
    specific_annual_revenue_last_year: 299000,
    ebitda: 209200,
    key_strength_1: `Rigorous, transparent recruitment process with no fees charged to candidates, ensuring integrity and quality.`,
    key_strength_2: `Serves a diverse portfolio of reputable clients across banking, telecommunications, retail, and hospitality.`,
    key_strength_3: `End-to-end workforce management covering recruitment, training, placement, payroll, and supervision.`,
    growth_opportunity_1: `Expanding geographic coverage beyond Central Java to major industrial hubs across Indonesia.`,
    growth_opportunity_2: `Developing digital HR technology solutions such as talent platforms and HRIS systems.`,
    growth_opportunity_3: `Diversifying into specialized staffing verticals such as IT staffing and healthcare workforce solutions.`,
    key_strengths_anonymous: [`Rigorous, transparent recruitment process with no fees charged to candidates, ensuring integrity and quality.`, `Serves a diverse portfolio of reputable clients across banking, telecommunications, retail, and hospitality.`, `End-to-end workforce management covering recruitment, training, placement, payroll, and supervision.`],
    specific_growth_opportunities: `• Expanding geographic coverage beyond Central Java to major industrial hubs across Indonesia.
• Developing digital HR technology solutions such as talent platforms and HRIS systems.
• Diversifying into specialized staffing verticals such as IT staffing and healthcare workforce solutions.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-014',
    listing_title_anonymous: `Integrated Jakarta property consultancy`,
    anonymous_business_description: `This Jakarta-based property consultancy firm, founded in 2009, provides integrated real estate services to multinational corporations, property developers, and institutional investors across Indonesia. The team brings decades of combined experience in property advisory, with senior leadership possessing over 20 years of expertise spanning global property brokerage, legal strategy, urban planning, and project management.

The company offers a comprehensive suite of nine service lines: office leasing and tenant representation, investment advisory, capital markets, property and asset management, retail solutions, valuation and advisory, project management, research and market analysis, and facility management. Operating from the Palma One Building in Kuningan, Jakarta, the firm has built a client roster of over 100 companies.`,
    asking_price: 700000,
    industry: 'Real Estate',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_13.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-23T08:00:00Z',
    updated_at: '2026-03-23T10:00:00Z',
    seller_id: 'sample-seller-014',
    annual_revenue_range: '$100K - $250K USD',
    specific_annual_revenue_last_year: 200000,
    ebitda: 140000,
    key_strength_1: `Seasoned leadership team with over 20 years of individual experience across property brokerage, legal advisory, urban planning, and project management.`,
    key_strength_2: `Unusually broad range of nine integrated real estate service lines.`,
    key_strength_3: `Large and diverse client base of over 100 companies, including multinational corporations.`,
    growth_opportunity_1: `Expanding into secondary Indonesian cities with emerging commercial real estate markets.`,
    growth_opportunity_2: `Leveraging data analytics and proptech innovations to enhance property valuation and digital client engagement.`,
    growth_opportunity_3: `Developing ASEAN regional advisory capabilities for cross-border investment strategy.`,
    key_strengths_anonymous: [`Seasoned leadership team with over 20 years of individual experience across property brokerage, legal advisory, urban planning, and project management.`, `Unusually broad range of nine integrated real estate service lines.`, `Large and diverse client base of over 100 companies, including multinational corporations.`],
    specific_growth_opportunities: `• Expanding into secondary Indonesian cities with emerging commercial real estate markets.
• Leveraging data analytics and proptech innovations to enhance property valuation and digital client engagement.
• Developing ASEAN regional advisory capabilities for cross-border investment strategy.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-015',
    listing_title_anonymous: `Viral English education provider`,
    anonymous_business_description: `This English language education provider operates both online and offline classes using the renowned Kampung Inggris immersive learning method aligned with CEFR standards. Based in Pare, Kediri, East Java, the company has grown to employ over 130 experienced tutors and has graduated more than 20,000 alumni from across Indonesia. It holds an official accreditation certificate from the regional education authority.

The company offers three core program categories: Speaking, Academic, and Testing (TOEFL and IELTS preparation). Classes cater to all levels from absolute beginners to advanced learners, serving both children and adults. Many tutors are scholarship recipients studying at universities in Australia, Europe, and the United States. The brand has over 2 million Instagram followers, and it provides additional services such as scholarship consultation and job interview preparation. A 100% money-back guarantee is offered.`,
    asking_price: 2093000,
    industry: 'Education',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_14.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-24T08:00:00Z',
    updated_at: '2026-03-24T10:00:00Z',
    seller_id: 'sample-seller-015',
    annual_revenue_range: '$500K - $1M USD',
    specific_annual_revenue_last_year: 598000,
    ebitda: 418600,
    key_strength_1: `Combines the proven Kampung Inggris immersive methodology with CEFR standards, supported by 130+ tutors including international scholarship recipients.`,
    key_strength_2: `Powerful brand with over 2 million Instagram followers and 20,000+ alumni.`,
    key_strength_3: `Bold 100% money-back guarantee, demonstrating high confidence in learning outcomes.`,
    growth_opportunity_1: `Scaling the online class platform to reach the Indonesian diaspora and English learners across Southeast Asia.`,
    growth_opportunity_2: `Developing structured B2B corporate training programs for companies.`,
    growth_opportunity_3: `Creating digital learning products such as mobile apps and self-paced courses for recurring revenue.`,
    key_strengths_anonymous: [`Combines the proven Kampung Inggris immersive methodology with CEFR standards, supported by 130+ tutors including international scholarship recipients.`, `Powerful brand with over 2 million Instagram followers and 20,000+ alumni.`, `Bold 100% money-back guarantee, demonstrating high confidence in learning outcomes.`],
    specific_growth_opportunities: `• Scaling the online class platform to reach the Indonesian diaspora and English learners across Southeast Asia.
• Developing structured B2B corporate training programs for companies.
• Creating digital learning products such as mobile apps and self-paced courses for recurring revenue.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-016',
    listing_title_anonymous: `VC-backed retail analytics platform`,
    anonymous_business_description: `This Kuala Lumpur-based company provides a cloud-based retail data analytics and business intelligence platform designed for SME retailers and F&B operators. The platform automatically captures, consolidates, analyzes, and visualizes receipt-level transaction data from POS systems, delivering real-time financial reporting and sales insights. It integrates with over 50 POS vendors and offers features including store performance monitoring, sales auditing, transaction pattern analysis, payment trend tracking, SKU efficiencies, and inventory management.

The platform aims to democratize data analytics by making it accessible to businesses of all sizes without the need for data science expertise. Case studies show one 30-outlet F&B chain generated an additional RM500,000 in monthly revenue through a single promotion informed by the platform. The company has raised $1.24M in funding and was recognized as a finalist in the Malaysia Kini Top in Tech awards.`,
    asking_price: 750000,
    industry: 'Information Technology (IT)',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_15.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-25T08:00:00Z',
    updated_at: '2026-03-25T10:00:00Z',
    seller_id: 'sample-seller-016',
    annual_revenue_range: '$500K - $1M USD',
    specific_annual_revenue_last_year: 500000,
    ebitda: null,
    key_strength_1: `Automated real-time data capture and analytics from POS systems, eliminating manual Excel-based reporting.`,
    key_strength_2: `Integration with over 50 POS vendors and ability to consolidate data from multiple systems into a single dashboard.`,
    key_strength_3: `Affordable, user-friendly platform requiring no data science expertise, making advanced retail analytics accessible to SMEs.`,
    growth_opportunity_1: `Expansion into additional Southeast Asian markets and beyond.`,
    growth_opportunity_2: `Development of enhanced AI-driven predictive analytics for demand forecasting and pricing optimization.`,
    growth_opportunity_3: `Deepening integration with e-commerce platforms for omnichannel analytics.`,
    key_strengths_anonymous: [`Automated real-time data capture and analytics from POS systems, eliminating manual Excel-based reporting.`, `Integration with over 50 POS vendors and ability to consolidate data from multiple systems into a single dashboard.`, `Affordable, user-friendly platform requiring no data science expertise, making advanced retail analytics accessible to SMEs.`],
    specific_growth_opportunities: `• Expansion into additional Southeast Asian markets and beyond.
• Development of enhanced AI-driven predictive analytics for demand forecasting and pricing optimization.
• Deepening integration with e-commerce platforms for omnichannel analytics.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-017',
    listing_title_anonymous: `Experienced Bandung software house`,
    anonymous_business_description: `This Bandung-based Indonesian software house has over 15 years of experience delivering IT solutions to startups and large enterprises. The company specializes in website development, mobile app development, digital marketing, UI/UX design, technology migration, system enhancement, IT audits, and onsite training. The team of 30+ developers is proficient in a broad technology stack spanning frontend frameworks (React, Next, Vue), backend (Node, Ruby on Rails, .Net, Golang, Laravel, Python), mobile (iOS, Android, Flutter, React Native), and emerging technologies such as AI, blockchain, and NFT launchpads.

The company serves a wide range of industries including fintech, healthcare, education, e-commerce, real estate, and IoT. Its client portfolio includes notable names such as Nutrifood and Waskita. The firm emphasizes fast response times, on-schedule delivery, and cost-effective solutions, having completed over 100 projects.`,
    asking_price: 196000,
    industry: 'Information Technology (IT)',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_16.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-26T08:00:00Z',
    updated_at: '2026-03-26T10:00:00Z',
    seller_id: 'sample-seller-017',
    annual_revenue_range: '$50K - $100K USD',
    specific_annual_revenue_last_year: 56000,
    ebitda: 39200,
    key_strength_1: `Extensive technology stack covering frontend, backend, mobile, blockchain, and AI, serving diverse project requirements.`,
    key_strength_2: `Over 15 years of experience and 100+ completed projects with both startups and enterprise clients.`,
    key_strength_3: `Cost-effective development services with fast response times and on-schedule delivery.`,
    growth_opportunity_1: `Expanding AI and machine learning service offerings to capitalize on enterprise demand for intelligent automation.`,
    growth_opportunity_2: `Strengthening international client acquisition across Southeast Asia and Australia.`,
    growth_opportunity_3: `Building proprietary SaaS products or reusable frameworks for recurring revenue.`,
    key_strengths_anonymous: [`Extensive technology stack covering frontend, backend, mobile, blockchain, and AI, serving diverse project requirements.`, `Over 15 years of experience and 100+ completed projects with both startups and enterprise clients.`, `Cost-effective development services with fast response times and on-schedule delivery.`],
    specific_growth_opportunities: `• Expanding AI and machine learning service offerings to capitalize on enterprise demand for intelligent automation.
• Strengthening international client acquisition across Southeast Asia and Australia.
• Building proprietary SaaS products or reusable frameworks for recurring revenue.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-018',
    listing_title_anonymous: `Scholarship prep with 97% success`,
    anonymous_business_description: `This Jakarta-based edutech company operates as a learning platform focused on global professional development, scholarship preparation, and study abroad guidance. Founded by women entrepreneurs, the company offers programs including a Scholarship Incubator, Global Programme Accelerator, standardized English test preparation (IELTS and TOEFL), essay checking, interview coaching, and pre-departure training. It also provides English for Specific Purposes courses tailored to professionals in fields such as engineering, nursing, aviation, and finance.

The platform has successfully sent over 800 clients to various countries, achieving a 97% success rate. It was named one of the Top 10 Best Companies Founded by Women from Indonesia in 2023 and has been covered by major Indonesian media. The company partners with Danacita for 0% installment payment options and offers both online and offline training through expert trainers.`,
    asking_price: 700000,
    industry: 'Education',
    location_country: 'Indonesia',
    location_city_region_general: 'Indonesia',
    image_urls: ['/assets/listings/row_17.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-27T08:00:00Z',
    updated_at: '2026-03-27T10:00:00Z',
    seller_id: 'sample-seller-018',
    annual_revenue_range: '$100K - $250K USD',
    specific_annual_revenue_last_year: 200000,
    ebitda: 140000,
    key_strength_1: `Exceptional 97% client success rate with 800+ clients sent abroad.`,
    key_strength_2: `End-to-end service from English proficiency training and test prep to scholarship application support and pre-departure preparation.`,
    key_strength_3: `Award-winning, women-founded company with strong media coverage and recognition.`,
    growth_opportunity_1: `Expanding the Work Abroad Programme for professionals seeking international career opportunities.`,
    growth_opportunity_2: `Scaling the Learning Management System into a fully digital, self-paced platform.`,
    growth_opportunity_3: `Developing corporate training partnerships with Indonesian enterprises for employee upskilling.`,
    key_strengths_anonymous: [`Exceptional 97% client success rate with 800+ clients sent abroad.`, `End-to-end service from English proficiency training and test prep to scholarship application support and pre-departure preparation.`, `Award-winning, women-founded company with strong media coverage and recognition.`],
    specific_growth_opportunities: `• Expanding the Work Abroad Programme for professionals seeking international career opportunities.
• Scaling the Learning Management System into a fully digital, self-paced platform.
• Developing corporate training partnerships with Indonesian enterprises for employee upskilling.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-019',
    listing_title_anonymous: `Vertically integrated medical supplier`,
    anonymous_business_description: `Founded in May 2007 and headquartered in Bandar Baru Bangi, Selangor, Malaysia, this company has grown into a leading provider of medical equipment and supplies serving the Malaysian healthcare sector. The company specializes in distributing a wide range of medical devices to hospitals, clinics, retail pharmacies, and other healthcare providers within both the private and government sectors. As an agent for several multinational companies, it distributes state-of-the-art medical equipment while maintaining strong relationships with clinicians and hospital administrators throughout Malaysia.

In addition to distribution, the company manufactures all of its products in-house at its own dedicated manufacturing plant, overseeing every step of the production process. Its product range includes wound care and skin care solutions. The company holds ISO 13485 certification and complies with Medical Device Regulatory 2012 and GDPMD standards.`,
    asking_price: 3094000,
    industry: 'Health & Wellness',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_18.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-28T08:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
    seller_id: 'sample-seller-019',
    annual_revenue_range: '$500K - $1M USD',
    specific_annual_revenue_last_year: 883873,
    ebitda: 618800,
    key_strength_1: `Vertically integrated model combining in-house manufacturing with distribution, enabling end-to-end quality control and ISO 13485 compliance.`,
    key_strength_2: `Nearly two decades of experience with strong relationships across private and government healthcare sectors in Malaysia.`,
    key_strength_3: `Comprehensive product portfolio spanning medical devices, wound care, and skin care.`,
    growth_opportunity_1: `Expanding distribution into neighboring Southeast Asian markets such as Indonesia, Thailand, and the Philippines.`,
    growth_opportunity_2: `Developing proprietary medical device innovations in wound care and skin care.`,
    growth_opportunity_3: `Growing the direct-to-consumer channel through e-commerce platforms.`,
    key_strengths_anonymous: [`Vertically integrated model combining in-house manufacturing with distribution, enabling end-to-end quality control and ISO 13485 compliance.`, `Nearly two decades of experience with strong relationships across private and government healthcare sectors in Malaysia.`, `Comprehensive product portfolio spanning medical devices, wound care, and skin care.`],
    specific_growth_opportunities: `• Expanding distribution into neighboring Southeast Asian markets such as Indonesia, Thailand, and the Philippines.
• Developing proprietary medical device innovations in wound care and skin care.
• Growing the direct-to-consumer channel through e-commerce platforms.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-020',
    listing_title_anonymous: `Listed global rubber manufacturer`,
    anonymous_business_description: `Founded in 1990 and headquartered in Petaling Jaya, Selangor, Malaysia, this publicly listed investment holding company (Bursa Malaysia: 7192) is principally involved in the development, manufacturing, and marketing of rubber and rubber-related compounds, serving clients in over 60 countries across five continents. The company operates through multiple segments including Rubber Compounds, Property Development, Re-Treading Services, and Trading. Key brands include Rubtek (specialized rubber compounds), Supercool (a tire sealant solution), and ToughTread (tire liners for off-road and heavy-duty vehicles).

Formerly known as Goodway Integrated Industries Berhad, the company was rebranded in December 2020. It operates manufacturing facilities in Nilai, Negeri Sembilan, and maintains global offices in Singapore and Dubai. The company provides tire retreading services, trades in tires and related products, and engages in property development and construction activities.`,
    asking_price: 35000000,
    industry: 'Manufacturing & Production',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_19.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-29T08:00:00Z',
    updated_at: '2026-03-29T10:00:00Z',
    seller_id: 'sample-seller-020',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 10000000,
    ebitda: 7000000,
    key_strength_1: `Extensive global distribution network spanning over 60 countries with regional offices in Malaysia, Singapore, and Dubai.`,
    key_strength_2: `Diversified product portfolio including proprietary brands (Rubtek, Supercool, ToughTread).`,
    key_strength_3: `Over three decades of experience in rubber compound manufacturing with continuous investment in technology and innovation.`,
    growth_opportunity_1: `Expanding healthcare segment through increased production of rubber gloves and medical-grade rubber products.`,
    growth_opportunity_2: `Leveraging the Supercool tire sealant brand in emerging markets where fleet maintenance cost reduction is a priority.`,
    growth_opportunity_3: `Pursuing strategic property development projects to diversify revenue streams.`,
    key_strengths_anonymous: [`Extensive global distribution network spanning over 60 countries with regional offices in Malaysia, Singapore, and Dubai.`, `Diversified product portfolio including proprietary brands (Rubtek, Supercool, ToughTread).`, `Over three decades of experience in rubber compound manufacturing with continuous investment in technology and innovation.`],
    specific_growth_opportunities: `• Expanding healthcare segment through increased production of rubber gloves and medical-grade rubber products.
• Leveraging the Supercool tire sealant brand in emerging markets where fleet maintenance cost reduction is a priority.
• Pursuing strategic property development projects to diversify revenue streams.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-021',
    listing_title_anonymous: `Multi-brand F&B group`,
    anonymous_business_description: `This is a purpose-driven food and beverage group based in Puchong, Selangor, Malaysia, operating under Rhombus Connexion Sdn Bhd. The company buys, creates, and operates iconic F&B brands, working with founders, creators, and investors to build dining and nightlife experiences. Its strength lies in blending creativity with operational discipline, turning concepts into living spaces that people connect with.

The group manages a diverse portfolio of over a dozen brands spanning multiple cuisines and formats, including The Beer Factory, Rama V (Thai fine dining), Dancing Fish, Thai Hou Sek, Suzie Wong, The Rabbit Hole, Bushido, Tap Room, Picaro, Paperkite, Common Space, and Tono Izakaya Singapore. Each brand is crafted with intention and powered by culture, ranging from neighborhood dining favorites to vibrant nightlife destinations across Malaysia and Singapore.`,
    asking_price: 84000000,
    industry: 'Restaurants & Food Service',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_20.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-10T08:00:00Z',
    updated_at: '2026-03-10T10:00:00Z',
    seller_id: 'sample-seller-021',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 24000000,
    ebitda: 16800000,
    key_strength_1: `Large, diversified portfolio of distinctive F&B brands across multiple cuisines and venue formats.`,
    key_strength_2: `Combines creative concept development with hands-on operational management for brand incubation and acquisition.`,
    key_strength_3: `Regional footprint extending beyond Malaysia into Singapore.`,
    growth_opportunity_1: `Expansion of proven brand concepts into additional Southeast Asian markets.`,
    growth_opportunity_2: `Leveraging the growing demand for experiential dining and nightlife.`,
    growth_opportunity_3: `Pursuing licensing and franchise models to scale successful brands more rapidly.`,
    key_strengths_anonymous: [`Large, diversified portfolio of distinctive F&B brands across multiple cuisines and venue formats.`, `Combines creative concept development with hands-on operational management for brand incubation and acquisition.`, `Regional footprint extending beyond Malaysia into Singapore.`],
    specific_growth_opportunities: `• Expansion of proven brand concepts into additional Southeast Asian markets.
• Leveraging the growing demand for experiential dining and nightlife.
• Pursuing licensing and franchise models to scale successful brands more rapidly.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-022',
    listing_title_anonymous: `ISO-certified government software vendor`,
    anonymous_business_description: `Founded in May 2013 and headquartered in Shah Alam, Selangor, Malaysia, this company is a custom software development firm that empowers growing businesses through tailored digital solutions. It specializes in designing, developing, installing, integrating, and maintaining web-based business applications using its proprietary SUFIA (Single Unified Framework for Internet Applications) platform, a Java-based server framework that accelerates development of secure, high-performing enterprise software.

The company holds MS ISO 9001:2015 certification and has been recognized with the SME100 Fast Moving Company Award. Its client roster includes prominent Malaysian organizations such as SIRIM QAS International, SIRIM Sdn Bhd, the Department of Statistics Malaysia (DOSM), and Lembaga Juruukur Bahan Malaysia. Services span system design, IT consultation, hands-on training, and ongoing maintenance support.`,
    asking_price: 1050000,
    industry: 'Information Technology (IT)',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_21.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-11T08:00:00Z',
    updated_at: '2026-03-11T10:00:00Z',
    seller_id: 'sample-seller-022',
    annual_revenue_range: '$250K - $500K USD',
    specific_annual_revenue_last_year: 300000,
    ebitda: 210000,
    key_strength_1: `Proprietary SUFIA framework enables rapid development and deployment of secure, enterprise-grade web and Android applications.`,
    key_strength_2: `ISO 9001:2015 certified with trusted relationships serving major Malaysian government agencies.`,
    key_strength_3: `Comprehensive service offering covering the full software lifecycle from consultation through implementation and maintenance.`,
    growth_opportunity_1: `Expanding client base beyond government and institutional clients into the broader Malaysian SME and private sector.`,
    growth_opportunity_2: `Developing mobile-first and cloud-native solutions for remote and hybrid work technologies.`,
    growth_opportunity_3: `Scaling regionally across Southeast Asia by leveraging its proven framework and compliance expertise.`,
    key_strengths_anonymous: [`Proprietary SUFIA framework enables rapid development and deployment of secure, enterprise-grade web and Android applications.`, `ISO 9001:2015 certified with trusted relationships serving major Malaysian government agencies.`, `Comprehensive service offering covering the full software lifecycle from consultation through implementation and maintenance.`],
    specific_growth_opportunities: `• Expanding client base beyond government and institutional clients into the broader Malaysian SME and private sector.
• Developing mobile-first and cloud-native solutions for remote and hybrid work technologies.
• Scaling regionally across Southeast Asia by leveraging its proven framework and compliance expertise.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-023',
    listing_title_anonymous: `VC-backed collectibles live marketplace`,
    anonymous_business_description: `Founded in 2022 and headquartered in Selangor, Malaysia, this company operates Asia's premier live bidding and community marketplace platform for collectibles. The platform enables users to buy, sell, and exchange a wide range of collectible items through livestream auctions, timed marketplace auctions, and direct listings. Categories include trading card games, Funko Pops, comics, Hot Wheels, Hot Toys, figurines, sneakers, luxury watches, and designer fashion.

The company has raised approximately $1.4 million in funding, with its pre-Series A round led by AC Ventures. It offers PSA grading submission services and enforces a zero-tolerance policy on counterfeits, with verification protocols for high-value items. The platform charges a standard 8% commission and has built a vibrant community of collectors supported by partnerships with hobby stores across the region.`,
    asking_price: 250000,
    industry: 'Retail & E-commerce',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_22.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-12T08:00:00Z',
    updated_at: '2026-03-12T10:00:00Z',
    seller_id: 'sample-seller-023',
    annual_revenue_range: '$100K - $250K USD',
    specific_annual_revenue_last_year: 166667,
    ebitda: null,
    key_strength_1: `Unique combination of livestream bidding, timed auctions, and traditional marketplace listings for collectors.`,
    key_strength_2: `Built-in authenticity safeguards including mandatory verification for high-value items and PSA grading services.`,
    key_strength_3: `Broad category coverage spanning trading cards, comics, toys, fashion, sneakers, and luxury goods.`,
    growth_opportunity_1: `Expanding geographically across Southeast Asia and into broader Asian markets.`,
    growth_opportunity_2: `Deepening partnerships with collectible brands and event organizers for exclusive product drops.`,
    growth_opportunity_3: `Introducing enhanced seller tools, analytics, and premium subscription tiers.`,
    key_strengths_anonymous: [`Unique combination of livestream bidding, timed auctions, and traditional marketplace listings for collectors.`, `Built-in authenticity safeguards including mandatory verification for high-value items and PSA grading services.`, `Broad category coverage spanning trading cards, comics, toys, fashion, sneakers, and luxury goods.`],
    specific_growth_opportunities: `• Expanding geographically across Southeast Asia and into broader Asian markets.
• Deepening partnerships with collectible brands and event organizers for exclusive product drops.
• Introducing enhanced seller tools, analytics, and premium subscription tiers.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-024',
    listing_title_anonymous: `Regional job distribution platform`,
    anonymous_business_description: `Founded in 2013 and headquartered in Malaysia, this company is one of the fastest-growing job distribution platforms in the Asia Pacific region, with a presence across Malaysia, Australia, Singapore, Hong Kong, the Philippines, and Indonesia. The platform allows employers to post a job once and have it distributed to up to 50 job sites, classified ads, and social network sites simultaneously, including LinkedIn, Indeed, Glassdoor, JobStreet, and Monster. It integrates a cloud-based applicant tracking system.

The platform serves over 20,000 employers and connects millions of job seekers with more than 100,000 job openings monthly, supported by 8 million users across the region. It has been recognized with multiple awards including Top 100 Private Technology Company. For job seekers, the platform is free and offers resume building, smart search filters, application tracking, and personalized recommendations. The company also organizes career fairs.`,
    asking_price: 35000000,
    industry: 'Information Technology (IT)',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_23.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-13T08:00:00Z',
    updated_at: '2026-03-13T10:00:00Z',
    seller_id: 'sample-seller-024',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 10000000,
    ebitda: 7000000,
    key_strength_1: `Powerful job distribution model posting to up to 50 partner sites from a single submission, maximizing employer reach.`,
    key_strength_2: `Large regional user base of 8 million job seekers across six countries.`,
    key_strength_3: `Integrated applicant tracking system and career fair events for end-to-end recruitment.`,
    growth_opportunity_1: `Expanding into additional markets to become a global job distribution platform.`,
    growth_opportunity_2: `Enhancing AI-powered matching and recommendation features.`,
    growth_opportunity_3: `Developing premium employer branding and talent analytics products.`,
    key_strengths_anonymous: [`Powerful job distribution model posting to up to 50 partner sites from a single submission, maximizing employer reach.`, `Large regional user base of 8 million job seekers across six countries.`, `Integrated applicant tracking system and career fair events for end-to-end recruitment.`],
    specific_growth_opportunities: `• Expanding into additional markets to become a global job distribution platform.
• Enhancing AI-powered matching and recommendation features.
• Developing premium employer branding and talent analytics products.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-025',
    listing_title_anonymous: `Pioneer integrated chiropractic center`,
    anonymous_business_description: `Established in 2006 in Kuala Lumpur, Malaysia, by American chiropractor Yama Zafer, D.C., this healthcare center was the first in Malaysia to integrate chiropractic care and physiotherapy under one roof. With nearly 30 years of clinical experience, the founder relocated to Malaysia with a vision to provide evidence-based, conservative alternatives to invasive surgical procedures. The center operates from two locations in KL: Bukit Damansara and Bandar Sri Damansara.

The center specializes in non-invasive spine, joint, and musculoskeletal care using evidence-based, non-rotatory chiropractic techniques including flexion-distraction, SOT, Thompson, Activator Methods, and upper cervical techniques. It was a pioneer in introducing spinal decompression therapy to Malaysia. Each patient receives a thorough consultation with physical, orthopedic, and neurological assessments before a customized treatment plan is developed.`,
    asking_price: 1985000,
    industry: 'Health & Wellness',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_24.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-14T08:00:00Z',
    updated_at: '2026-03-14T10:00:00Z',
    seller_id: 'sample-seller-025',
    annual_revenue_range: '$500K - $1M USD',
    specific_annual_revenue_last_year: 567108,
    ebitda: 397000,
    key_strength_1: `Pioneer in Malaysia for integrating chiropractic and physiotherapy within a single clinical workflow.`,
    key_strength_2: `Multiple evidence-based, non-rotatory chiropractic techniques tailored to individual conditions.`,
    key_strength_3: `Nearly two decades of clinical presence in KL with deep expertise in conservative spine and joint care.`,
    growth_opportunity_1: `Expanding to additional locations within Malaysia, particularly Penang, Johor Bahru, and other major urban centers.`,
    growth_opportunity_2: `Developing telehealth consultations and digital rehabilitation programs.`,
    growth_opportunity_3: `Building partnerships with sports organizations, corporate wellness programs, and insurance providers.`,
    key_strengths_anonymous: [`Pioneer in Malaysia for integrating chiropractic and physiotherapy within a single clinical workflow.`, `Multiple evidence-based, non-rotatory chiropractic techniques tailored to individual conditions.`, `Nearly two decades of clinical presence in KL with deep expertise in conservative spine and joint care.`],
    specific_growth_opportunities: `• Expanding to additional locations within Malaysia, particularly Penang, Johor Bahru, and other major urban centers.
• Developing telehealth consultations and digital rehabilitation programs.
• Building partnerships with sports organizations, corporate wellness programs, and insurance providers.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-026',
    listing_title_anonymous: `Malaysia's top news aggregator`,
    anonymous_business_description: `This is Malaysia's leading content aggregation platform, offering users a centralized hub to access news, articles, podcasts, and videos from over 400 trusted publishers, websites, and independent content creators. Available as a mobile app with over 2.4 million installs, the platform delivers content in three languages (English, Malay, and Mandarin) across categories including local news, world news, politics, business, food, entertainment, technology, sports, lifestyle, and wellness.

The platform features real-time content updates, push notification alerts, a HOT feed for trending stories, home screen widgets, night mode, and compact reading mode. It runs a Creator program for independent content creators to publish and earn revenue. A premium subscription provides an ad-free experience, while the app links directly to original sources from publishers such as The Straits Times, The Edge, Malay Mail, BFM 89.9, and South China Morning Post.`,
    asking_price: 3500000,
    industry: 'Media & Communications',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_25.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-15T08:00:00Z',
    updated_at: '2026-03-15T10:00:00Z',
    seller_id: 'sample-seller-026',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 1000000,
    ebitda: 700000,
    key_strength_1: `Aggregates content from over 400 trusted publishers in multiple languages, providing comprehensive news coverage in one place.`,
    key_strength_2: `Robust Creator program empowering independent writers to reach millions of users and monetize their work.`,
    key_strength_3: `User-friendly interface with real-time alerts, trending highlights, night mode, and compact mode.`,
    growth_opportunity_1: `Expanding the premium subscription tier with additional exclusive features.`,
    growth_opportunity_2: `Growing the content creator ecosystem to attract more niche and independent voices.`,
    growth_opportunity_3: `Extending reach into new Southeast Asian markets by leveraging multilingual capabilities.`,
    key_strengths_anonymous: [`Aggregates content from over 400 trusted publishers in multiple languages, providing comprehensive news coverage in one place.`, `Robust Creator program empowering independent writers to reach millions of users and monetize their work.`, `User-friendly interface with real-time alerts, trending highlights, night mode, and compact mode.`],
    specific_growth_opportunities: `• Expanding the premium subscription tier with additional exclusive features.
• Growing the content creator ecosystem to attract more niche and independent voices.
• Extending reach into new Southeast Asian markets by leveraging multilingual capabilities.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-027',
    listing_title_anonymous: `Licensed migrant remittance provider`,
    anonymous_business_description: `Founded in 2008 in Batu Pahat, Johor, Malaysia, this is a licensed money services business regulated by Bank Negara Malaysia. The company was established by a group of experienced professionals from the banking, manufacturing, services, and IT sectors. Its mission is to provide money transfer services and innovative financial payment convenience to millions of migrant workers across various sectors including factories, agriculture, construction, and remote plantations throughout Malaysia.

The company offers a complete range of money transfer solutions including person-to-person (P2P) remittance, corporate business payment solutions (B2B), and e-remittance through apps and web platforms. Its vision centers on providing integrated payment solutions using technology to serve underbanked and unbanked individuals and corporations who lack access to traditional bank branches.`,
    asking_price: 28000000,
    industry: 'Banking & Finance',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_26.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-16T08:00:00Z',
    updated_at: '2026-03-16T10:00:00Z',
    seller_id: 'sample-seller-027',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 8000000,
    ebitda: 5600000,
    key_strength_1: `Fully regulated and licensed by Bank Negara Malaysia, providing confidence in the legitimacy of transactions.`,
    key_strength_2: `Specialized focus on serving migrant workers and underbanked populations across diverse sectors.`,
    key_strength_3: `Multiple remittance channels including physical branches, e-remittance apps, and B2B cross-border payment solutions.`,
    growth_opportunity_1: `Expanding digital remittance capabilities and mobile app adoption.`,
    growth_opportunity_2: `Increasing the branch network and corridor coverage to serve more remittance destinations.`,
    growth_opportunity_3: `Developing partnerships with fintech platforms and international agents to enhance cross-border payment speed and reduce costs.`,
    key_strengths_anonymous: [`Fully regulated and licensed by Bank Negara Malaysia, providing confidence in the legitimacy of transactions.`, `Specialized focus on serving migrant workers and underbanked populations across diverse sectors.`, `Multiple remittance channels including physical branches, e-remittance apps, and B2B cross-border payment solutions.`],
    specific_growth_opportunities: `• Expanding digital remittance capabilities and mobile app adoption.
• Increasing the branch network and corridor coverage to serve more remittance destinations.
• Developing partnerships with fintech platforms and international agents to enhance cross-border payment speed and reduce costs.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-028',
    listing_title_anonymous: `Award-winning creative agency`,
    anonymous_business_description: `This is an award-winning, full-service creative and branding agency headquartered in Shah Alam, Selangor, Malaysia, with an additional office in Downtown Dubai, UAE. The agency positions itself as a strategic partner for businesses facing challenges in communicating effectively with their target audiences, offering expertise across six core areas: digital and social media, brand consultancy, design, web and technology, performance media, and public relations.

The agency has earned recognition through multiple industry awards, including Gold at the Marketing Excellence Awards, Gold at the Arkies Awards for esports marketing, and Bronze for Boutique Agency of the Year. Its client roster includes prominent brands such as Yoodo, Allianz Malaysia, Panasonic, CIMB, Laneige, Suria KLCC, Big Bad Wolf, and BookXcess. The company also operates a four-day work week.`,
    asking_price: 1800000,
    industry: 'Marketing & Advertising',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_27.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-01-17T08:00:00Z',
    updated_at: '2026-03-17T10:00:00Z',
    seller_id: 'sample-seller-028',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 1200000,
    ebitda: null,
    key_strength_1: `Multiple industry award wins across marketing, digital campaigns, and esports marketing.`,
    key_strength_2: `Impressive roster of major Malaysian and international brand clients across finance, telecom, retail, and consumer goods.`,
    key_strength_3: `Full-service capabilities covering digital, brand consultancy, design, web technology, performance media, and PR.`,
    growth_opportunity_1: `Leveraging the Dubai office to expand into the broader Middle Eastern market.`,
    growth_opportunity_2: `Deepening capabilities in AI-driven marketing, influencer commerce, and data analytics.`,
    growth_opportunity_3: `Scaling the team to attract enterprise-level clients while maintaining boutique agility.`,
    key_strengths_anonymous: [`Multiple industry award wins across marketing, digital campaigns, and esports marketing.`, `Impressive roster of major Malaysian and international brand clients across finance, telecom, retail, and consumer goods.`, `Full-service capabilities covering digital, brand consultancy, design, web technology, performance media, and PR.`],
    specific_growth_opportunities: `• Leveraging the Dubai office to expand into the broader Middle Eastern market.
• Deepening capabilities in AI-driven marketing, influencer commerce, and data analytics.
• Scaling the team to attract enterprise-level clients while maintaining boutique agility.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-029',
    listing_title_anonymous: `Early-stage metacommerce platform`,
    anonymous_business_description: `This is a metacommerce platform based in Petaling Jaya, Selangor, Malaysia. The platform combines life simulation, social interaction, and e-commerce within a 3D virtual metaverse where users can customize avatars, decorate apartments, socialize, and participate in multiplayer mini-games. Founded by Charles Tang, who previously launched InstanteStore (a DIY e-commerce platform used by SMEs in over 85 countries processing more than US$1.8 billion in sales), the company aims to redefine how users interact with games and online shopping.

The platform is available on Steam (PC) and as a mobile app. It features an in-game currency system called Younits, and also operates Yooca, a metacommerce component where digital interaction translates into physical, real-world rewards. Built for a generation that creates, shares, and builds communities online, the platform provides collaborative spaces for content creators and serves as a hub for both virtual and physical commerce.`,
    asking_price: 40000,
    industry: 'Information Technology (IT)',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_28.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-02-18T08:00:00Z',
    updated_at: '2026-03-18T10:00:00Z',
    seller_id: 'sample-seller-029',
    annual_revenue_range: '< $50K USD',
    specific_annual_revenue_last_year: 27000,
    ebitda: null,
    key_strength_1: `Unique metacommerce model blending gaming, social interaction, and e-commerce in an immersive 3D environment.`,
    key_strength_2: `Founded by an experienced entrepreneur with a proven track record in e-commerce (InstanteStore, $1.8B+ in sales processed).`,
    key_strength_3: `Cross-platform availability on PC (Steam) and mobile with a dedicated development team.`,
    growth_opportunity_1: `Expanding brand partnerships and integrating more real-world retailers into the Yooca metacommerce ecosystem.`,
    growth_opportunity_2: `Optimizing performance across devices and expanding the mini-game library.`,
    growth_opportunity_3: `Growing the content creator ecosystem and community-driven features for long-term retention.`,
    key_strengths_anonymous: [`Unique metacommerce model blending gaming, social interaction, and e-commerce in an immersive 3D environment.`, `Founded by an experienced entrepreneur with a proven track record in e-commerce (InstanteStore, $1.8B+ in sales processed).`, `Cross-platform availability on PC (Steam) and mobile with a dedicated development team.`],
    specific_growth_opportunities: `• Expanding brand partnerships and integrating more real-world retailers into the Yooca metacommerce ecosystem.
• Optimizing performance across devices and expanding the mini-game library.
• Growing the content creator ecosystem and community-driven features for long-term retention.`,
    listing_type: 'full_acquisition',
  },
  {
    id: 'listing-030',
    listing_title_anonymous: `Cross-border automation engineering firm`,
    anonymous_business_description: `Founded in 2016 in Penang, Malaysia by Jon Ooi, this automation and custom equipment engineering company provides one-stop manufacturing solutions for clients worldwide. The company specializes in designing, building, and installing non-standard, customized assembly lines, precision fabrication equipment, and factory automation components for industries including solar energy, automotive, life sciences, aviation, and consumer electronics. In 2021, the company expanded internationally by establishing a subsidiary in Suzhou, China.

The Malaysian team consists of 32 members including mechanical engineers, electrical and software engineers, and project managers. The Chinese team adds further engineering and project management capacity. The company's service model covers the full project lifecycle from conceptual design and proof of concept to pilot lines, duplication lines, project management, and after-sales support. Clients include SMT Technologies, Swoboda Technologies, and First Solar.`,
    asking_price: 19250000,
    industry: 'Manufacturing & Production',
    location_country: 'Malaysia',
    location_city_region_general: 'Malaysia',
    image_urls: ['/assets/listings/row_29.png'],
    status: 'active',
    is_seller_verified: true,
    listing_verification_status: 'verified',
    created_at: '2026-03-19T08:00:00Z',
    updated_at: '2026-03-19T10:00:00Z',
    seller_id: 'sample-seller-030',
    annual_revenue_range: '$1M+ USD',
    specific_annual_revenue_last_year: 5500000,
    ebitda: 3850000,
    key_strength_1: `End-to-end engineering service covering concept development, proof of concept, pilot and duplication lines, and after-sales support.`,
    key_strength_2: `Strong specialization across high-value industries (solar, automotive, life sciences, aviation, consumer electronics).`,
    key_strength_3: `International presence with operations in both Malaysia and China.`,
    growth_opportunity_1: `Capitalizing on the global push toward renewable energy and electric vehicles.`,
    growth_opportunity_2: `Scaling the Suzhou operation to capture a larger share of the Asian manufacturing automation market.`,
    growth_opportunity_3: `Investing in smart manufacturing technologies such as robotics, IoT, and AI-driven quality control.`,
    key_strengths_anonymous: [`End-to-end engineering service covering concept development, proof of concept, pilot and duplication lines, and after-sales support.`, `Strong specialization across high-value industries (solar, automotive, life sciences, aviation, consumer electronics).`, `International presence with operations in both Malaysia and China.`],
    specific_growth_opportunities: `• Capitalizing on the global push toward renewable energy and electric vehicles.
• Scaling the Suzhou operation to capture a larger share of the Asian manufacturing automation market.
• Investing in smart manufacturing technologies such as robotics, IoT, and AI-driven quality control.`,
    listing_type: 'full_acquisition',
  },
];

// Transform for detail view (matches API single listing response format)
export function transformSampleForDetail(listing: typeof sampleListings[number]) {
  return {
    id: listing.id,
    title: listing.listing_title_anonymous,
    short_description: listing.anonymous_business_description,
    asking_price: listing.asking_price,
    industry: listing.industry,
    location_country: listing.location_country,
    location_city: listing.location_city_region_general,
    images: listing.image_urls,
    status: listing.status,
    verification_status: listing.is_seller_verified ? 'verified' : 'pending',
    listing_type: listing.listing_type || 'full_acquisition',
    created_at: listing.created_at,
    updated_at: listing.updated_at,
    seller_id: listing.seller_id,
    annual_revenue_range: listing.annual_revenue_range,
    verified_annual_revenue: listing.specific_annual_revenue_last_year,
    ebitda: listing.ebitda,
    key_strength_1: listing.key_strength_1,
    key_strength_2: listing.key_strength_2,
    key_strength_3: listing.key_strength_3,
    growth_opportunity_1: listing.growth_opportunity_1,
    growth_opportunity_2: listing.growth_opportunity_2,
    growth_opportunity_3: listing.growth_opportunity_3,
    key_strengths_anonymous: listing.key_strengths_anonymous,
    specific_growth_opportunities: listing.specific_growth_opportunities,
  };
}

// Transform for list view (matches API response format)
export function transformSampleForList(listing: typeof sampleListings[number]) {
  return {
    id: listing.id,
    title: listing.listing_title_anonymous,
    short_description: listing.anonymous_business_description,
    asking_price: listing.asking_price,
    industry: listing.industry,
    location_country: listing.location_country,
    location_city: listing.location_city_region_general,
    images: listing.image_urls,
    status: listing.status,
    verification_status: listing.is_seller_verified ? 'verified' : 'pending',
    listing_type: listing.listing_type || 'full_acquisition',
    created_at: listing.created_at,
    updated_at: listing.updated_at,
    seller_id: listing.seller_id,
    annual_revenue_range: listing.annual_revenue_range,
    verified_annual_revenue: listing.specific_annual_revenue_last_year,
    key_strength_1: listing.key_strength_1,
    key_strength_2: listing.key_strength_2,
    key_strength_3: listing.key_strength_3,
    growth_opportunity_1: listing.growth_opportunity_1,
    growth_opportunity_2: listing.growth_opportunity_2,
    growth_opportunity_3: listing.growth_opportunity_3,
    key_strengths_anonymous: listing.key_strengths_anonymous,
    specific_growth_opportunities: listing.specific_growth_opportunities,
  };
}
