version: '3.8'

# This file overrides the default Supabase Docker Compose configuration.
# It's the standard way to inject environment variables for local development.

services:
  auth:
    environment:
      # This explicitly tells the Supabase auth service to trust requests
      # coming from localhost, which is required for local email sending to work.
      GOTRUE_MAILER_EXTERNAL_HOSTS: "127.0.0.1,localhost,host.docker.internal"

      # This increases the log level for easier debugging if issues persist.
      GOTRUE_LOG_LEVEL: "debug"
