-- Create test listings for the user
INSERT INTO listings (
  seller_id,
  listing_title_anonymous,
  industry,
  location_country,
  location_city_region_general,
  anonymous_business_description,
  key_strengths_anonymous,
  annual_revenue_range,
  net_profit_margin_range,
  asking_price,
  deal_structure_looking_for,
  reason_for_selling_anonymous,
  business_model,
  year_established,
  number_of_employees,
  business_website_url,
  status,
  is_seller_verified,
  specific_annual_revenue_last_year,
  specific_net_profit_last_year,
  adjusted_cash_flow
) VALUES
(
  '2fad0689-95a5-413b-9a38-5885f14f6a7b',
  'Profitable SaaS Business for Sale',
  'Technology',
  'United States',
  'San Francisco, CA',
  'A thriving software-as-a-service business with recurring revenue and strong growth potential.',
  '["Recurring revenue model", "Strong customer retention", "Scalable technology"]',
  '$500K - $1M',
  '20-30%',
  750000,
  '["Asset purchase", "Stock purchase"]',
  'Founder moving to new venture',
  'B2B SaaS with monthly subscriptions',
  2020,
  '10-20',
  'https://example-saas.com',
  'verified_anonymous',
  true,
  875000,
  218750,
  200000
),
(
  '2fad0689-95a5-413b-9a38-5885f14f6a7b',
  'E-commerce Store - Health & Wellness',
  'E-commerce',
  'United States',
  'Austin, TX',
  'Established online store selling health and wellness products with strong brand recognition.',
  '["Strong brand", "Loyal customer base", "High margins"]',
  '$1M - $2M',
  '15-25%',
  1200000,
  '["Asset purchase"]',
  'Owner retirement',
  'Direct-to-consumer e-commerce',
  2018,
  '5-10',
  'https://example-health.com',
  'active',
  false,
  1450000,
  290000,
  275000
);

-- Verify listings were created
SELECT id, listing_title_anonymous, industry, asking_price, status FROM listings
WHERE seller_id = '2fad0689-95a5-413b-9a38-5885f14f6a7b';
