-- Create admin profile for existing auth user
INSERT INTO user_profiles (
  id,
  email,
  full_name,
  phone_number,
  country,
  role,
  verification_status,
  is_paid,
  is_email_verified,
  email_verified_at,
  is_onboarding_completed,
  onboarding_completed_at,
  email_notifications_general,
  email_notifications_inquiries,
  email_notifications_listing_updates,
  email_notifications_system
) VALUES (
  (SELECT id FROM auth.users WHERE email = 'admin@nobridge.com'),
  'admin@nobridge.com',
  'Admin User',
  '1234567890',
  'United States',
  'admin',
  'verified',
  false,
  true,
  NOW(),
  true,
  NOW(),
  true,
  true,
  true,
  true
) ON CONFLICT (email) DO UPDATE SET
  role = 'admin',
  verification_status = 'verified',
  is_email_verified = true,
  is_onboarding_completed = true;
